"""Docker provider plugin entry point.

This module is the ``docker`` setuptools entry point, so it is imported for every
``mngr`` invocation while plugins are loaded. It must therefore stay free of the
docker SDK: the backend implementation (``imbue.mngr_docker.backend``) and the
operator CLI (``imbue.mngr_docker.cli``) import the provider instance, which pulls
``docker`` and ``requests`` in, so they are imported lazily -- only when a docker
provider is actually operated -- via the ``LazyProviderBackend`` loader and
``LazyProviderCliGroup`` below.
"""

from collections.abc import Sequence
from pathlib import Path
from typing import Final

import click

from imbue.mngr.cli.doc_links import imbue_mngr_doc_url
from imbue.mngr.cli.help_formatter import CommandHelpMetadata
from imbue.mngr.cli.help_formatter import add_pager_help_option
from imbue.mngr.config.data_types import MngrContext
from imbue.mngr.interfaces.help_topic import DocFile
from imbue.mngr.interfaces.help_topic import TopicHelpPage
from imbue.mngr.interfaces.provider_backend import LazyProviderBackend
from imbue.mngr.interfaces.provider_backend import ProviderBackendInterface
from imbue.mngr.providers.deploy_utils import collect_provider_profile_files
from imbue.mngr.utils.click_utils import LazyProviderCliGroup
from imbue.mngr_docker import hookimpl
from imbue.mngr_docker.config import DockerProviderConfig
from imbue.mngr_docker.constants import DOCKER_BACKEND_NAME
from imbue.mngr_docker.constants import DOCKER_BUILD_ARGS_HELP
from imbue.mngr_docker.constants import DOCKER_START_ARGS_HELP

# SSH key and host key file names stored in the docker provider's profile directory.
# These are generated by load_or_create_ssh_keypair() and should not be baked into deployment images.
# Note that it is ok to include the host keys, since those are already present remotely (that's the whole point)
_DOCKER_EXCLUDED_PROFILE_FILES: Final[frozenset[str]] = frozenset(
    {
        "docker_ssh_key",
        "docker_ssh_key.pub",
        "known_hosts",
    }
)

# The usage doc ships inside the package so `mngr help docker_usage` works from a wheel install.
_DOCKER_USAGE_DOC_PATH: Final[Path] = Path(__file__).parent / "docs" / "docker_usage.md"
_DOCKER_USAGE_DOC_REPO_PATH: Final[str] = "libs/mngr_docker/imbue/mngr_docker/docs/docker_usage.md"


def _load_docker_backend() -> type[ProviderBackendInterface]:
    """Import and return the docker provider backend class (pulls the docker SDK)."""
    from imbue.mngr_docker.backend import DockerProviderBackend

    return DockerProviderBackend


def _load_docker_cli_group() -> click.Group:
    """Import and return the ``mngr docker`` operator command group (pulls the docker SDK)."""
    from imbue.mngr_docker.cli import docker_group

    return docker_group


@hookimpl
def register_provider_backend() -> LazyProviderBackend:
    """Register the docker provider backend lazily so startup skips the docker SDK."""
    return LazyProviderBackend(
        name=DOCKER_BACKEND_NAME,
        config_class=DockerProviderConfig,
        load=_load_docker_backend,
        build_args_help=DOCKER_BUILD_ARGS_HELP,
        start_args_help=DOCKER_START_ARGS_HELP,
    )


# The group's own help page is registered here, at plugin load, so `mngr --help`
# and the doc generator see it without importing the lazily-loaded command module.
_DOCKER_GROUP_HELP: Final[CommandHelpMetadata] = CommandHelpMetadata(
    key="docker",
    one_line_description="Docker-provider-specific commands",
    synopsis="mngr docker [resize] [OPTIONS]",
    description="""Commands that only make sense for hosts on the docker provider (containers
on a local or remote Docker daemon). Everything else about a docker host is
managed through the ordinary commands (create, start, stop, destroy, list).""",
    examples=(("Give a docker host 4 CPUs and 8 GB of memory", "mngr docker resize my-host --cpus 4 --memory 8g"),),
    see_also=(
        ("create", "Create an agent; -s --cpus / -s --memory set a docker host's size at creation"),
        ("list", "List agents; host.resource shows each host's recorded size"),
    ),
)
_DOCKER_GROUP_HELP.register()


@hookimpl
def register_cli_commands() -> Sequence[click.Command]:
    """Register the ``mngr docker ...`` operator command group lazily."""
    # The lazy group parses the group-level options itself, so it (not the real
    # group it loads) is what carries the pager-backed -h/--help.
    return [
        add_pager_help_option(
            LazyProviderCliGroup(
                name="docker",
                load=_load_docker_cli_group,
                help=_DOCKER_GROUP_HELP.one_line_description,
            )
        )
    ]


@hookimpl
def get_files_for_deploy(
    mngr_ctx: MngrContext,
    include_user_settings: bool,
    include_project_settings: bool,
    repo_root: Path,
) -> dict[Path, Path | str]:
    """Include docker provider profile files, excluding SSH keypairs.

    SSH keypairs (docker_ssh_key, host_key, and their .pub companions) and
    known_hosts are excluded because they are environment-specific secrets.
    The deployed environment generates fresh keypairs via
    load_or_create_ssh_keypair().
    """
    if not include_user_settings:
        return {}
    return collect_provider_profile_files(mngr_ctx, str(DOCKER_BACKEND_NAME), _DOCKER_EXCLUDED_PROFILE_FILES)


@hookimpl
def register_help_topics() -> Sequence[TopicHelpPage]:
    """Register the ``mngr help docker_usage`` topic page."""
    return [
        TopicHelpPage(
            key="docker_usage",
            one_line_description="Using Docker",
            body=DocFile(path=_DOCKER_USAGE_DOC_PATH, source_url=imbue_mngr_doc_url(_DOCKER_USAGE_DOC_REPO_PATH)),
            see_also=(
                ("create", "Create and run an agent"),
                ("docker", _DOCKER_GROUP_HELP.one_line_description),
            ),
        ),
    ]
