/**
 * Latchkey gateway extension: HTTP endpoints for managing pending
 * permission requests.
 *
 * Endpoints:
 *   POST   /permission-requests              Create a new permission request.
 *                                            Body: JSON object with the string
 *                                            fields "agent_id", "service_name",
 *                                            "rationale". The ``request_id`` is
 *                                            generated by the extension (a
 *                                            random UUID-shaped string) and
 *                                            returned in the response object.
 *   GET    /permission-requests              List all pending permission requests as
 *                                            newline-delimited JSON (one object per
 *                                            line, application/x-ndjson). With the
 *                                            optional query parameter ?follow=true,
 *                                            the connection is kept open and every
 *                                            request newly created via this
 *                                            extension's POST endpoint is streamed
 *                                            as an additional JSONL line until the
 *                                            client disconnects. Filesystem changes
 *                                            made by anything other than the POST
 *                                            handler are not observed.
 *   DELETE /permission-requests/<request_id> Remove the named permission request.
 *
 * Each pending request is stored as a single JSON file at
 * `<latchkey-directory>/permission_requests/<request_id>.json`, where
 * `<latchkey-directory>` is `LATCHKEY_DIRECTORY` if set, otherwise
 * `~/.latchkey`.
 *
 * NOTE: extension requests still go through the gateway's permission
 * check, so callers must have a rule that allows them to talk to
 * `latchkey-self.invalid` on the relevant method/path.
 *
 * There are potential race conditions but we ignore them for now.
 */

import { randomBytes, randomUUID } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

const COLLECTION_PATH = '/permission-requests';
const ITEM_PATH_PREFIX = '/permission-requests/';
const REQUEST_FILE_SUFFIX = '.json';
const PERSISTED_REQUEST_FIELDS = ['request_id', 'agent_id', 'service_name', 'rationale'];
const POST_BODY_FIELDS = ['agent_id', 'service_name', 'rationale'];
const VALID_REQUEST_ID_PATTERN = /^[A-Za-z0-9._-]+$/;

class PermissionRequestsExtensionError extends Error {
  constructor(statusCode, message) {
    super(message);
    this.name = 'PermissionRequestsExtensionError';
    this.statusCode = statusCode;
  }
}

class InvalidRequestBodyError extends PermissionRequestsExtensionError {
  constructor(detail) {
    super(400, `Invalid request body: ${detail}`);
    this.name = 'InvalidRequestBodyError';
  }
}

class InvalidRequestIdError extends PermissionRequestsExtensionError {
  constructor(detail) {
    super(400, `Invalid request_id: ${detail}`);
    this.name = 'InvalidRequestIdError';
  }
}

class RequestNotFoundError extends PermissionRequestsExtensionError {
  constructor(requestId) {
    super(404, `Permission request '${requestId}' not found.`);
    this.name = 'RequestNotFoundError';
  }
}

function resolveLatchkeyDirectory() {
  const directoryOverride = process.env.LATCHKEY_DIRECTORY;
  if (directoryOverride && directoryOverride.length > 0) {
    return directoryOverride;
  }
  return join(homedir(), '.latchkey');
}

function resolvePermissionRequestsDirectory() {
  return join(resolveLatchkeyDirectory(), 'permission_requests');
}

function validateRequestId(rawValue) {
  if (typeof rawValue !== 'string' || rawValue.length === 0) {
    throw new InvalidRequestIdError('must be a non-empty string.');
  }
  if (!VALID_REQUEST_ID_PATTERN.test(rawValue)) {
    throw new InvalidRequestIdError(
      "must match /^[A-Za-z0-9._-]+$/ to be safe to use as a filename.",
    );
  }
  if (rawValue === '.' || rawValue === '..') {
    throw new InvalidRequestIdError("must not be '.' or '..'.");
  }
  return rawValue;
}

function requestFilePath(requestId) {
  return join(resolvePermissionRequestsDirectory(), `${requestId}${REQUEST_FILE_SUFFIX}`);
}

async function readRequestBody(request) {
  const chunks = [];
  for await (const chunk of request) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf-8');
}

/**
 * Parse the POST body. The body must contain ``agent_id``,
 * ``service_name``, and ``rationale`` as non-empty strings; any other
 * field (including a caller-supplied ``request_id``) is rejected so
 * the server side stays the single source of truth on identity.
 */
async function parsePermissionRequestBody(request) {
  const raw = await readRequestBody(request);
  if (raw.trim().length === 0) {
    throw new InvalidRequestBodyError('expected a JSON object, got empty body.');
  }
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new InvalidRequestBodyError(`not valid JSON: ${message}`);
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new InvalidRequestBodyError('expected a JSON object.');
  }
  for (const field of POST_BODY_FIELDS) {
    const value = parsed[field];
    if (typeof value !== 'string' || value.length === 0) {
      throw new InvalidRequestBodyError(
        `field '${field}' is required and must be a non-empty string.`,
      );
    }
  }
  const extraneousFields = Object.keys(parsed).filter(
    (key) => !POST_BODY_FIELDS.includes(key),
  );
  if (extraneousFields.length > 0) {
    throw new InvalidRequestBodyError(
      `unknown field(s): ${extraneousFields.map((name) => `'${name}'`).join(', ')}.`,
    );
  }
  return {
    agent_id: parsed.agent_id,
    service_name: parsed.service_name,
    rationale: parsed.rationale,
  };
}

function ensureDirectory(directory) {
  if (!existsSync(directory)) {
    mkdirSync(directory, { recursive: true, mode: 0o700 });
  }
}

function writeRequestFileAtomic(filePath, value) {
  const directory = dirname(filePath);
  ensureDirectory(directory);
  const tempPath = join(
    directory,
    `.tmp.permission-request.${randomBytes(6).toString('hex')}`,
  );
  const serialized = `${JSON.stringify(value, null, 2)}\n`;
  try {
    writeFileSync(tempPath, serialized, { encoding: 'utf-8', mode: 0o600 });
    renameSync(tempPath, filePath);
  } catch (error) {
    try {
      unlinkSync(tempPath);
    } catch {
      // best-effort cleanup
    }
    const message = error instanceof Error ? error.message : String(error);
    throw new PermissionRequestsExtensionError(
      500,
      `Failed to write ${filePath}: ${message}`,
    );
  }
}

/**
 * Read a single permission-request file. Returns `null` when the file is
 * unreadable or its contents do not match the expected shape, so a stray
 * non-JSON file in the directory cannot break listing.
 */
function readRequestFile(filePath) {
  let raw;
  try {
    raw = readFileSync(filePath, 'utf-8');
  } catch {
    return null;
  }
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    return null;
  }
  for (const field of PERSISTED_REQUEST_FIELDS) {
    if (typeof parsed[field] !== 'string') {
      return null;
    }
  }
  return {
    request_id: parsed.request_id,
    agent_id: parsed.agent_id,
    service_name: parsed.service_name,
    rationale: parsed.rationale,
  };
}

function listPermissionRequests() {
  const directory = resolvePermissionRequestsDirectory();
  if (!existsSync(directory)) {
    return [];
  }
  const fileNames = readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .filter((entry) => entry.name.endsWith(REQUEST_FILE_SUFFIX))
    .filter((entry) => !entry.name.startsWith('.'))
    .map((entry) => entry.name)
    .sort();
  const result = [];
  for (const fileName of fileNames) {
    const value = readRequestFile(join(directory, fileName));
    if (value !== null) {
      result.push(value);
    }
  }
  return result;
}

function decodeRequestIdSegment(rawSegment) {
  try {
    return decodeURIComponent(rawSegment);
  } catch {
    return rawSegment;
  }
}

function parseRequestUrl(requestUrl) {
  // The request URL is path-and-query only, so use a placeholder origin to
  // make WHATWG URL parsing happy.
  return new URL(requestUrl ?? '', 'http://placeholder.invalid');
}

function parseRoute(requestUrl) {
  const pathOnly = parseRequestUrl(requestUrl).pathname;
  if (pathOnly === COLLECTION_PATH || pathOnly === `${COLLECTION_PATH}/`) {
    return { kind: 'collection' };
  }
  if (pathOnly.startsWith(ITEM_PATH_PREFIX)) {
    const remainder = pathOnly.slice(ITEM_PATH_PREFIX.length);
    if (remainder.length === 0 || remainder.includes('/')) {
      return { kind: 'unhandled' };
    }
    return { kind: 'item', requestIdFromPath: decodeRequestIdSegment(remainder) };
  }
  return { kind: 'unhandled' };
}

function parseBooleanQueryParam(rawValue) {
  if (rawValue === null || rawValue === undefined) return false;
  const normalized = rawValue.toLowerCase();
  return normalized === '1' || normalized === 'true' || normalized === 'yes';
}

function sendJson(response, statusCode, payload) {
  const body = `${JSON.stringify(payload, null, 2)}\n`;
  response.writeHead(statusCode, {
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(body, 'utf-8'),
  });
  response.end(body);
}

function sendError(response, statusCode, message) {
  sendJson(response, statusCode, { error: message });
}

function writeJsonLine(response, value) {
  response.write(`${JSON.stringify(value)}\n`);
}

/**
 * In-process subscribers that get invoked synchronously after each
 * successful POST to /permission-requests. Each follow-stream adds itself
 * to this set on connect and removes itself on disconnect.
 */
const newRequestListeners = new Set();

/**
 * Cleanup callbacks for every active follow stream. The `stop` lifecycle
 * hook iterates this set to terminate streams promptly on gateway
 * shutdown.
 */
const activeFollowStreamCleanups = new Set();

function subscribeToNewRequests(listener) {
  newRequestListeners.add(listener);
  return () => {
    newRequestListeners.delete(listener);
  };
}

function notifyNewRequest(value) {
  for (const listener of newRequestListeners) {
    try {
      listener(value);
    } catch {
      // A misbehaving listener must not break the POST handler or other
      // listeners.
    }
  }
}

/**
 * Stream permission requests until the client disconnects.
 */
function streamPermissionRequests(request, response) {
  response.writeHead(200, { 'Content-Type': 'application/x-ndjson; charset=utf-8' });
  response.flushHeaders();

  const unsubscribe = subscribeToNewRequests((value) => {
    writeJsonLine(response, value);
  });
  for (const value of listPermissionRequests()) {
    writeJsonLine(response, value);
  }

  return new Promise((resolve) => {
    let cleanedUp = false;
    const cleanup = () => {
      if (cleanedUp) return;
      cleanedUp = true;
      activeFollowStreamCleanups.delete(cleanup);
      unsubscribe();
      if (!response.writableEnded) {
        response.end();
      }
      resolve();
    };
    activeFollowStreamCleanups.add(cleanup);
    request.on('close', cleanup);
  });
}

/**
 * Gateway lifecycle hook: end every active follow stream so the gateway
 * can shut down promptly.
 */
export function stop() {
  for (const cleanup of [...activeFollowStreamCleanups]) {
    cleanup();
  }
}

/**
 * Generate a server-side request_id. We use a UUIDv4 hex so the result
 * is filename-safe under VALID_REQUEST_ID_PATTERN and trivially unique
 * across concurrent POSTs.
 */
function generateRequestId() {
  return randomUUID().replace(/-/g, '');
}

async function handleCreateRequest(request, response) {
  const body = await parsePermissionRequestBody(request);
  // Loop on the astronomically rare UUID collision so we never overwrite
  // an existing pending request.
  let requestId = generateRequestId();
  let filePath = requestFilePath(requestId);
  while (existsSync(filePath)) {
    requestId = generateRequestId();
    filePath = requestFilePath(requestId);
  }
  validateRequestId(requestId);
  const persisted = {
    request_id: requestId,
    agent_id: body.agent_id,
    service_name: body.service_name,
    rationale: body.rationale,
  };
  writeRequestFileAtomic(filePath, persisted);
  notifyNewRequest(persisted);
  sendJson(response, 201, persisted);
}

function handleListRequests(request, response, follow) {
  if (follow) {
    return streamPermissionRequests(request, response);
  }
  response.writeHead(200, { 'Content-Type': 'application/x-ndjson; charset=utf-8' });
  for (const value of listPermissionRequests()) {
    writeJsonLine(response, value);
  }
  response.end();
  return Promise.resolve();
}

function handleDeleteRequest(response, rawRequestId) {
  const requestId = validateRequestId(rawRequestId);
  const filePath = requestFilePath(requestId);
  if (!existsSync(filePath)) {
    throw new RequestNotFoundError(requestId);
  }
  try {
    unlinkSync(filePath);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new PermissionRequestsExtensionError(
      500,
      `Failed to delete ${filePath}: ${message}`,
    );
  }
  response.writeHead(204);
  response.end();
}

export default async function permissionRequestsExtension(request, response) {
  const route = parseRoute(request.url);
  const method = (request.method ?? 'GET').toUpperCase();

  try {
    if (route.kind === 'collection' && method === 'GET') {
      const followParam = parseRequestUrl(request.url).searchParams.get('follow');
      await handleListRequests(request, response, parseBooleanQueryParam(followParam));
      return true;
    }
    if (route.kind === 'collection' && method === 'POST') {
      await handleCreateRequest(request, response);
      return true;
    }
    if (route.kind === 'item' && method === 'DELETE') {
      handleDeleteRequest(response, route.requestIdFromPath);
      return true;
    }
  } catch (error) {
    if (error instanceof PermissionRequestsExtensionError) {
      sendError(response, error.statusCode, error.message);
      return true;
    }
    const message = error instanceof Error ? error.message : String(error);
    sendError(response, 500, `Internal error: ${message}`);
    return true;
  }
  return false;
}
