help:
    @just --list

build target:
  @if [ "{{target}}" = "flexmux" ]; then \
    cd libs/flexmux/frontend && pnpm install && pnpm run build; \
  elif [ -d "apps/{{target}}" ]; then \
    uvx --from build pyproject-build --installer=uv --outdir=dist --wheel apps/{{target}}; \
  elif [ -d "libs/{{target}}" ]; then \
    uvx --from build pyproject-build --installer=uv --outdir=dist --wheel libs/{{target}}; \
  else \
    echo "Error: Target '{{target}}' not found in apps/ or libs/"; \
    exit 1; \
  fi

run target:
  @if [ "{{target}}" = "flexmux" ]; then \
    uv run flexmux; \
  else \
    echo "Error: No run command defined for '{{target}}'"; \
    exit 1; \
  fi

# Generate .dockerignore from .gitignore. Kept as a generator (not a
# committed file) so .dockerignore stays in lockstep with .gitignore and
# never needs manual sync. The generator strips:
#   - `/.dockerignore` self-reference so offload's copy_untracked_files
#     picks up this gitignored-but-not-dockerignored file;
#   - `/libs/mngr/imbue/mngr/resources/Dockerfile.release` so offload
#     0.8.1's stricter staging phase can find the generated release
#     Dockerfile (0.7.x was laxer and didn't filter it out). The file is
#     gitignored because it's generated by _generate-release-dockerfile
#     right before offload runs; it must be visible to the offload build
#     context even though it's never committed.
[private]
_generate-dockerignore:
    grep -vE '^/?\.dockerignore$|^/libs/mngr/imbue/mngr/resources/Dockerfile\.release$' .gitignore > .dockerignore

# Generate Dockerfile.release from Dockerfile + Dockerfile.release.extras so the
# two Dockerfiles stay in sync without duplicating the base layers. Strips the
# trailing CMD from Dockerfile; the .extras file provides its own CMD.
[private]
_generate-release-dockerfile:
    #!/bin/bash
    set -ueo pipefail
    base=libs/mngr/imbue/mngr/resources/Dockerfile
    extras=libs/mngr/imbue/mngr/resources/Dockerfile.release.extras
    out=libs/mngr/imbue/mngr/resources/Dockerfile.release
    # Everything from the base Dockerfile up to (not including) the first CMD line.
    awk '/^CMD/{exit} {print}' "$base" > "$out"
    cat "$extras" >> "$out"

# Run tests on Modal via Offload
test-offload args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT
    # offload 0.8.1 manages build context + image caching via git notes; no
    # tarballs, patches, or local cache-key files needed.
    offload -c offload-modal.toml {{args}} run || [[ $? -eq 2 ]]

    # Copy results to the main worktree so new worktrees inherit baselines via COPY mode.
    MAIN_WORKTREE=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
    if [ -f test-results/junit.xml ] && [ -n "$MAIN_WORKTREE" ] && [ "$MAIN_WORKTREE" != "$(pwd)" ]; then
        mkdir -p "$MAIN_WORKTREE/test-results"
        cp test-results/junit.xml "$MAIN_WORKTREE/test-results/junit.xml"
    fi

# Run acceptance tests on Modal via Offload
test-offload-acceptance args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT
    # MODAL_IMAGE_BUILDER_VERSION=2025.06 is required for enable_docker support (Docker-in-Docker alpha).
    MODAL_IMAGE_BUILDER_VERSION=2025.06 offload -c offload-modal-acceptance.toml {{args}} run \
        --env "MODAL_TOKEN_ID=$MODAL_TOKEN_ID" \
        --env "MODAL_TOKEN_SECRET=$MODAL_TOKEN_SECRET" || [[ $? -eq 2 ]]

# Run release tests on Modal via Offload (with Docker-in-Docker)
test-offload-release args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    : "${ANTHROPIC_API_KEY:?must be set}"

    # Regenerate Dockerfile.release from Dockerfile + Dockerfile.release.extras
    # so the two stay in sync.
    just _generate-release-dockerfile
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT

    # MODAL_IMAGE_BUILDER_VERSION=2025.06 is required for enable_docker support (Docker-in-Docker alpha).
    MODAL_IMAGE_BUILDER_VERSION=2025.06 offload -c offload-modal-release.toml {{args}} run \
        --env "MODAL_TOKEN_ID=$MODAL_TOKEN_ID" \
        --env "MODAL_TOKEN_SECRET=$MODAL_TOKEN_SECRET" \
        --env "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" \
        --env "IS_RELEASE=1" || [[ $? -eq 2 ]]

    # Copy results to the main worktree so new worktrees inherit baselines via COPY mode.
    MAIN_WORKTREE=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
    if [ -f test-results/junit.xml ] && [ -n "$MAIN_WORKTREE" ] && [ "$MAIN_WORKTREE" != "$(pwd)" ]; then
        mkdir -p "$MAIN_WORKTREE/test-results"
        cp test-results/junit.xml "$MAIN_WORKTREE/test-results/junit.xml"
    fi

# Xdist parallelism args for local dev recipes. Kept out of pyproject addopts
# so they don't leak into offload sandboxes (which run `-p no:xdist`).
_parallel := "-n 4 --dist=worksteal --max-worker-restart=0"
# Default mark filter for local unit + integration recipes. Kept out of
# pyproject addopts because it would collide with offload-modal-acceptance
# (which runs the opposite filter). A later -m on CLI overrides this.
_skip_acceptance_and_release := "-m 'not acceptance and not release'"

test-unit:
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --cov-report=html --ignore-glob="**/test_*.py" --cov-fail-under=36

test-integration:
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --cov-report=html --cov-fail-under=80

# Examples:
#   just test-quick
#   just test-quick libs/mngr
#   just test-quick libs/mngr/.../foo_test.py::test_bar
#   just test-quick "libs/mngr -m 'not tmux and not modal'"
# Note: pass complex argument strings (anything with spaces, like -m exprs)
# as ONE outer-quoted argument. Variadic {{args}} splits on whitespace
# and drops inner quoting, which would truncate `-m 'a and b'` to `-m a`.
# The recipe's default `-m 'not acceptance and not release'` can be
# overridden by supplying a `-m` inside args (later CLI -m wins).
# Fast local iteration: forwards args to pytest. No coverage, xdist-parallel.
test-quick args="":
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --no-cov {{args}}

test-acceptance:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=600 uv run pytest {{_parallel}} --no-cov -m "no release"

test-release:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=1200 uv run pytest {{_parallel}} --no-cov -m "acceptance or not acceptance"

# Generate test timings for pytest-split (run periodically to keep timings up to date. Runs all acceptance and release)
test-timings:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=6000 uv run pytest --no-cov -n 0 -m "acceptance or not acceptance" --store-durations

# useful for running against a single test, regardless of how it is marked
test target:
  PYTEST_MAX_DURATION_SECONDS=600 uv run pytest -sv --no-cov -n 0 -m "acceptance or not acceptance" "{{target}}"

# Download the Tailwind Play CDN JS bundle for the minds desktop client.
# Idempotent and SHA-pinned via apps/minds/scripts/fetch_tailwind.sh -- the
# same script also runs automatically as a pnpm `postinstall` hook, so
# normally you do not need to invoke this recipe. Use it when you want to
# force-verify the file or after nuking the static/ dir.
minds-tailwind:
  bash apps/minds/scripts/fetch_tailwind.sh

# Sync vendor/mngr in forever-claude-template to this repo's HEAD and commit
# in FCT. Default FCT path is $HOME/project/forever-claude-template; override
# by passing a positional arg. Run from this repo on the branch you want to
# vendor (typically main); the recipe archives HEAD, replaces vendor/mngr/
# contents with that snapshot, and commits in FCT. Does not push. Aborts if
# FCT has any uncommitted changes -- resolve them first. The full release
# flow (release branches, push, merge to main) is the release-minds skill.
sync-vendor-mngr fct="$HOME/project/forever-claude-template":
    #!/bin/bash
    set -ueo pipefail
    fct="{{fct}}"
    if [ ! -d "$fct/vendor/mngr" ]; then
        echo "Error: $fct/vendor/mngr not found"
        exit 1
    fi
    if [ -n "$(git -C "$fct" status --porcelain)" ]; then
        echo "Error: $fct has uncommitted changes; resolve them first:"
        git -C "$fct" status --short
        exit 1
    fi
    branch=$(git rev-parse --abbrev-ref HEAD)
    short=$(git rev-parse --short HEAD)
    full=$(git rev-parse HEAD)
    tarball=$(mktemp)
    trap "rm -f $tarball" EXIT
    git archive --format=tar HEAD > "$tarball"
    cd "$fct/vendor/mngr"
    rm -rf ./* ./.[!.]*
    tar -xf "$tarball"
    cd "$fct"
    git add -A vendor/mngr/
    if git diff --cached --quiet -- vendor/mngr/; then
        echo "vendor/mngr already in sync with mngr ${short}; nothing to commit"
        exit 0
    fi
    git commit -m "Sync vendor/mngr to ${branch} (${short})" -m "Tracks ${full} in mngr."
    echo "Synced vendor/mngr to ${branch} (${short}). To publish: (cd $fct && git push origin ${branch})"


# === Modal deploy / minds iteration helpers ===
#
# All of these read per-env config from .minds/<env>/ (gitignored). The
# `<env>` name is whatever directory you have under .minds/ -- e.g.
# `production`, `staging`. The matching templates live in .minds/template/.

# Validate that .minds/<env>/*.sh files declare every key the templates
# declare, and print the modal-secret commands that `push-secrets` would
# run. Does NOT touch Modal. Run this first when you change a template
# or add a new per-env file.
push-secrets-dry-run env="production":
    uv run scripts/push_modal_secrets.py {{env}} --dry-run

# Upsert every per-env Modal secret declared in .minds/template/ for the
# given env. Reads .minds/<env>/<service>.sh and writes <service>-<env>
# secrets to Modal. Idempotent (uses --force).
push-secrets env="production":
    uv run scripts/push_modal_secrets.py {{env}}

# Deploy the remote_service_connector Modal app for the given env.
# Does NOT push secrets first -- run `just push-secrets <env>` if any
# .minds/<env>/*.sh files have changed since the last deploy.
deploy-connector env="production":
    bash scripts/deploy_remote_service_connector.sh {{env}}

# Deploy the modal_litellm proxy Modal app for the given env.
# Does NOT push secrets first -- run `just push-secrets <env>` if
# .minds/<env>/litellm.sh has changed since the last deploy.
deploy-litellm env="production":
    bash scripts/deploy_litellm.sh {{env}}

# Push every per-env secret then deploy every Modal app for the given
# env. Equivalent to push-secrets + deploy-connector + deploy-litellm.
deploy-all env="production": (push-secrets env) (deploy-connector env) (deploy-litellm env)

# Start the minds desktop client (electron) in dev mode.
# Run `pnpm install` inside apps/minds/ once before first use.
minds-start:
    cd apps/minds && pnpm start

# Build the minds desktop client distributable (slow; uses todesktop).
minds-build:
    cd apps/minds && pnpm build

# Provision N Vultr-backed pool hosts and register them in the pool DB
# at the given version tag (matched by /hosts/lease). Sources
# .minds/<env>/.env and .minds/<env>/neon.sh so DATABASE_URL,
# VULTR_API_KEY, etc. are available to the python script. Override
# `template_repo` if your forever-claude-template clone lives outside
# the default path.
create-pool-hosts count="1" env="production" version="v0.1.0" template_repo="$HOME/project/forever-claude-template":
    #!/bin/bash
    set -ueo pipefail
    set -a
    . .minds/{{env}}/.env
    . .minds/{{env}}/neon.sh
    set +a
    uv run python apps/remote_service_connector/scripts/create_pool_hosts.py \
        --count {{count}} --version {{version}} \
        --management-public-key-file .minds/{{env}}/pool_management_key/id_ed25519.pub \
        --template-dir {{template_repo}}

# Destroy and remove every host in the pool with status='released'.
# Sources .minds/<env>/neon.sh for DATABASE_URL.
cleanup-pool-hosts env="production":
    #!/bin/bash
    set -ueo pipefail
    set -a
    . .minds/{{env}}/neon.sh
    set +a
    uv run python apps/remote_service_connector/scripts/cleanup_released_hosts.py \
        --database-url "$DATABASE_URL"
