help:
    @just --list

build target:
  @if [ -d "apps/{{target}}" ]; then \
    uvx --from build pyproject-build --installer=uv --outdir=dist --wheel apps/{{target}}; \
  elif [ -d "libs/{{target}}" ]; then \
    uvx --from build pyproject-build --installer=uv --outdir=dist --wheel libs/{{target}}; \
  else \
    echo "Error: Target '{{target}}' not found in apps/ or libs/"; \
    exit 1; \
  fi

# Generate .dockerignore from .gitignore. Kept as a generator (not a
# committed file) so .dockerignore stays in lockstep with .gitignore and
# never needs manual sync. The generator strips:
#   - `/.dockerignore` self-reference so offload's copy_untracked_files
#     picks up this gitignored-but-not-dockerignored file;
#   - `/libs/mngr/imbue/mngr/resources/Dockerfile.release` so offload
#     0.8.1's stricter staging phase can find the generated release
#     Dockerfile (0.7.x was laxer and didn't filter it out). The file is
#     gitignored because it's generated by _generate-release-dockerfile
#     right before offload runs; it must be visible to the offload build
#     context even though it's never committed.
[private]
_generate-dockerignore:
    grep -vE '^/?\.dockerignore$|^/libs/mngr/imbue/mngr/resources/Dockerfile\.release$' .gitignore > .dockerignore

# Generate Dockerfile.release from Dockerfile + Dockerfile.release.extras so the
# two Dockerfiles stay in sync without duplicating the base layers. Strips the
# trailing CMD from Dockerfile; the .extras file provides its own CMD.
[private]
_generate-release-dockerfile:
    #!/bin/bash
    set -ueo pipefail
    base=libs/mngr/imbue/mngr/resources/Dockerfile
    extras=libs/mngr/imbue/mngr/resources/Dockerfile.release.extras
    out=libs/mngr/imbue/mngr/resources/Dockerfile.release
    # Everything from the base Dockerfile up to (not including) the first CMD line.
    awk '/^CMD/{exit} {print}' "$base" > "$out"
    cat "$extras" >> "$out"

# Run tests on Modal via Offload
test-offload args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT
    offload -c offload-modal.toml run --trace \
        --env "GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-}" \
        --env "GITHUB_REF_NAME=${GITHUB_REF_NAME:-}" {{args}} || [[ $? -eq 2 ]]

    # Copy results to the main worktree so new worktrees inherit baselines via COPY mode.
    MAIN_WORKTREE=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
    if [ -f test-results/junit.xml ] && [ -n "$MAIN_WORKTREE" ] && [ "$MAIN_WORKTREE" != "$(pwd)" ]; then
        mkdir -p "$MAIN_WORKTREE/test-results"
        cp test-results/junit.xml "$MAIN_WORKTREE/test-results/junit.xml"
    fi

# Run acceptance tests on Modal via Offload
test-offload-acceptance args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT
    # MODAL_IMAGE_BUILDER_VERSION=2025.06 is required for enable_docker support (Docker-in-Docker alpha).
    MODAL_IMAGE_BUILDER_VERSION=2025.06 offload -c offload-modal-acceptance.toml run --trace \
        --env "MODAL_TOKEN_ID=$MODAL_TOKEN_ID" \
        --env "MODAL_TOKEN_SECRET=$MODAL_TOKEN_SECRET" \
        --env "GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-}" \
        --env "GITHUB_REF_NAME=${GITHUB_REF_NAME:-}" {{args}} || [[ $? -eq 2 ]]

# Run release tests on Modal via Offload (with Docker-in-Docker)
test-offload-release args="":
    #!/bin/bash
    set -ueo pipefail
    : "${MODAL_TOKEN_ID:?must be set}"
    : "${MODAL_TOKEN_SECRET:?must be set}"
    : "${ANTHROPIC_API_KEY:?must be set}"

    # Regenerate Dockerfile.release from Dockerfile + Dockerfile.release.extras
    # so the two stay in sync.
    just _generate-release-dockerfile
    just _generate-dockerignore
    trap "rm -f .dockerignore" EXIT

    # MODAL_IMAGE_BUILDER_VERSION=2025.06 is required for enable_docker support (Docker-in-Docker alpha).
    MODAL_IMAGE_BUILDER_VERSION=2025.06 offload -c offload-modal-release.toml run --trace \
        --env "MODAL_TOKEN_ID=$MODAL_TOKEN_ID" \
        --env "MODAL_TOKEN_SECRET=$MODAL_TOKEN_SECRET" \
        --env "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" \
        --env "IS_RELEASE=1" \
        --env "GITHUB_HEAD_REF=${GITHUB_HEAD_REF:-}" \
        --env "GITHUB_REF_NAME=${GITHUB_REF_NAME:-}" {{args}} || [[ $? -eq 2 ]]

    # Copy results to the main worktree so new worktrees inherit baselines via COPY mode.
    MAIN_WORKTREE=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
    if [ -f test-results/junit.xml ] && [ -n "$MAIN_WORKTREE" ] && [ "$MAIN_WORKTREE" != "$(pwd)" ]; then
        mkdir -p "$MAIN_WORKTREE/test-results"
        cp test-results/junit.xml "$MAIN_WORKTREE/test-results/junit.xml"
    fi

# Xdist parallelism args for local dev recipes. Kept out of pyproject addopts
# so they don't leak into offload sandboxes (which run `-p no:xdist`).
_parallel := "-n 4 --dist=worksteal --max-worker-restart=0"
# Default mark filter for local unit + integration recipes. Kept out of
# pyproject addopts because it would collide with offload-modal-acceptance
# (which runs the opposite filter). A later -m on CLI overrides this.
_skip_acceptance_and_release := "-m 'not acceptance and not release'"

test-unit:
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --cov-report=html --ignore-glob="**/test_*.py" --cov-fail-under=36

test-integration:
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --cov-report=html --cov-fail-under=80

# Examples:
#   just test-quick
#   just test-quick libs/mngr
#   just test-quick libs/mngr/.../foo_test.py::test_bar
#   just test-quick "libs/mngr -m 'not tmux and not modal'"
# Note: pass complex argument strings (anything with spaces, like -m exprs)
# as ONE outer-quoted argument. Variadic {{args}} splits on whitespace
# and drops inner quoting, which would truncate `-m 'a and b'` to `-m a`.
# The recipe's default `-m 'not acceptance and not release'` can be
# overridden by supplying a `-m` inside args (later CLI -m wins).
# Fast local iteration: forwards args to pytest. No coverage, xdist-parallel.
test-quick args="":
  uv run pytest {{_parallel}} {{_skip_acceptance_and_release}} --no-cov {{args}}

test-acceptance:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=600 uv run pytest {{_parallel}} --no-cov -m "no release"

test-release:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=1200 uv run pytest {{_parallel}} --no-cov -m "acceptance or not acceptance"

# Generate test timings for pytest-split (run periodically to keep timings up to date. Runs all acceptance and release)
test-timings:
  # when running these locally, we set the max duration super high just so that we don't fail (which makes it harder to see the errors)
  PYTEST_MAX_DURATION_SECONDS=6000 uv run pytest --no-cov -n 0 -m "acceptance or not acceptance" --store-durations

# useful for running against a single test, regardless of how it is marked
test target:
  PYTEST_MAX_DURATION_SECONDS=600 uv run pytest -sv --no-cov -n 0 -m "acceptance or not acceptance" "{{target}}"

# Download the Tailwind Play CDN JS bundle for the minds desktop client.
# Idempotent and SHA-pinned via apps/minds/scripts/fetch_tailwind.sh -- the
# same script also runs automatically as a pnpm `postinstall` hook, so
# normally you do not need to invoke this recipe. Use it when you want to
# force-verify the file or after nuking the static/ dir.
minds-tailwind:
  bash apps/minds/scripts/fetch_tailwind.sh

# Sync vendor/mngr in forever-claude-template to this repo's HEAD and commit
# in FCT. Default FCT path is $HOME/project/forever-claude-template; override
# by passing a positional arg. Run from this repo on the branch you want to
# vendor (typically main); the recipe archives HEAD, replaces vendor/mngr/
# contents with that snapshot, and commits in FCT. Does not push. Aborts if
# FCT has any uncommitted changes -- resolve them first. The full release
# flow (release branches, push, merge to main) is the release-minds skill.
sync-vendor-mngr fct="$HOME/project/forever-claude-template":
    #!/bin/bash
    set -ueo pipefail
    fct="{{fct}}"
    if [ ! -d "$fct/vendor/mngr" ]; then
        echo "Error: $fct/vendor/mngr not found"
        exit 1
    fi
    if [ -n "$(git -C "$fct" status --porcelain)" ]; then
        echo "Error: $fct has uncommitted changes; resolve them first:"
        git -C "$fct" status --short
        exit 1
    fi
    branch=$(git rev-parse --abbrev-ref HEAD)
    short=$(git rev-parse --short HEAD)
    full=$(git rev-parse HEAD)
    tarball=$(mktemp)
    trap "rm -f $tarball" EXIT
    git archive --format=tar HEAD > "$tarball"
    cd "$fct/vendor/mngr"
    rm -rf ./* ./.[!.]*
    tar -xf "$tarball"
    cd "$fct"
    git add -A vendor/mngr/
    if git diff --cached --quiet -- vendor/mngr/; then
        echo "vendor/mngr already in sync with mngr ${short}; nothing to commit"
        exit 0
    fi
    git commit -m "Sync vendor/mngr to ${branch} (${short})" -m "Tracks ${full} in mngr."
    echo "Synced vendor/mngr to ${branch} (${short}). To publish: (cd $fct && git push origin ${branch})"


# === Modal deploy / minds iteration helpers ===
#
# All of these read per-env config from .minds/<env>/ (gitignored). The
# `<env>` name is whatever directory you have under .minds/ -- e.g.
# `production`, `staging`. The matching templates live in .minds/template/.

# Validate that .minds/<env>/*.sh files declare every key the templates
# declare, and print the modal-secret commands that `push-secrets` would
# run. Does NOT touch Modal. Run this first when you change a template
# or add a new per-env file.
push-secrets-dry-run env="production":
    uv run scripts/push_modal_secrets.py {{env}} --dry-run

# Upsert every per-env Modal secret declared in .minds/template/ for the
# given env. Reads .minds/<env>/<service>.sh and writes <service>-<env>
# secrets to Modal. Idempotent (uses --force).
push-secrets env="production":
    uv run scripts/push_modal_secrets.py {{env}}

# Deploy the remote_service_connector Modal app for the given env.
# Does NOT push secrets first -- run `just push-secrets <env>` if any
# .minds/<env>/*.sh files have changed since the last deploy.
deploy-connector env="production":
    bash scripts/deploy_remote_service_connector.sh {{env}}

# Deploy the modal_litellm proxy Modal app for the given env.
# Does NOT push secrets first -- run `just push-secrets <env>` if
# .minds/<env>/litellm.sh has changed since the last deploy.
deploy-litellm env="production":
    bash scripts/deploy_litellm.sh {{env}}

# Push every per-env secret then deploy every Modal app for the given
# env. Equivalent to push-secrets + deploy-connector + deploy-litellm.
deploy-all env="production": (push-secrets env) (deploy-connector env) (deploy-litellm env)

# One-shot recipe for dev iteration on the minds stack. Combines the
# vendor/mngr sync and the Electron launch into a single command so the
# very first Create after starting the app picks up your local mngr code
# rather than whatever stale snapshot the FCT worktree was created from.
#
# Why the sync step is necessary on EVERY startup:
#   The desktop client's Create flow (apps/minds/.../agent_creator.py)
#   rsyncs the FCT worktree (including vendor/mngr/) into a temp clone
#   and ships THAT into the Docker container. mngr inside the container
#   is editable-installed from /code/vendor/mngr/. So if vendor/mngr/ in
#   the worktree is older than the mngr code you actually want to test
#   (e.g. a new field you added to settings.toml), the container's mngr
#   will reject your settings and the bootstrap's chat-agent create call
#   will fail. The user-visible symptom is an empty workspace with "No
#   conversation data" in the chat panel. Re-syncing on every startup
#   makes the first Create work without a follow-up propagate_changes.
#
# Why rsync (not `git archive` like `just sync-vendor-mngr`):
#   - rsync carries uncommitted mngr changes through, so you don't have
#     to commit just to test something.
#   - rsync leaves the FCT worktree's git state as a normal diff (visible
#     to `git status`) instead of creating a commit you'd then have to
#     undo. Use `just sync-vendor-mngr` for the release-flow sync that
#     does want to commit.
#
# Why MINDS_ROOT_NAME=devminds:
#   Keeps dev state under ~/.devminds/ (separate from prod ~/.minds/) so
#   running this recipe doesn't clobber the prod minds profile and the
#   minds bootstrap derives MNGR_HOST_DIR / MNGR_PREFIX correctly.
#
# Override agent_name / branch via positional args -- they're forwarded
# verbatim to `just minds-start`:
#   just devminds-start agent_name=foo branch=some-branch
devminds-start agent_name="mindtest" branch="":
    #!/bin/bash
    set -ueo pipefail
    fct_wt="$(pwd)/.external_worktrees/forever-claude-template"
    if [ ! -e "$fct_wt/.git" ]; then
        echo "error: no FCT worktree at $fct_wt" >&2
        echo "       run \`git -C ~/project/forever-claude-template worktree add -b <branch> $fct_wt <base>\`" >&2
        echo "       (e.g. base = josh/start-minds) before re-running devminds-start." >&2
        exit 2
    fi
    vendor_mngr="$fct_wt/vendor/mngr"
    mkdir -p "$vendor_mngr"
    echo "Syncing $(pwd) -> $vendor_mngr (rsync, uncommitted-friendly, no FCT commit)"
    # Exclusions must match _RSYNC_MANUAL_EXCLUDES + _GITIGNORE_RSYNC_FILTER
    # in libs/mngr_imbue_cloud/.../cli/admin.py and apps/minds/.../cli/pool.py,
    # and the RSYNC_EXCLUDES array in apps/minds/scripts/propagate_changes --
    # all four paths populate the same vendor/mngr/ destination.
    #
    # `--filter=:- .gitignore` reads .gitignore at each directory level under
    # the source and applies its exclude rules, so __pycache__, .venv,
    # node_modules, .test_output, .mypy_cache, .ruff_cache, .pytest_cache,
    # .external_worktrees, etc. are all covered without listing them here.
    # `.git` and `uv.lock` aren't in .gitignore (`.git` is git's internal
    # dir; `uv.lock` is intentionally committed but each install context
    # regenerates its own), so we exclude those manually.
    rsync -a --delete \
        --filter=':- .gitignore' \
        --exclude=.git \
        --exclude=uv.lock \
        ./ "$vendor_mngr/"
    export MINDS_ROOT_NAME=devminds
    # Delegate to minds-start to keep the env-loading / MINDS_WORKSPACE_*
    # setup / PID-file gating logic in one place.
    just minds-start "{{agent_name}}" "{{branch}}"

# Start the minds desktop client (electron) in dev mode.
# Sources .env (for ANTHROPIC_API_KEY etc.) and sets MINDS_WORKSPACE_*
# env vars so the create-form auto-fills "repository", "name", and
# "branch":
#   MINDS_WORKSPACE_GIT_URL = .external_worktrees/forever-claude-template/
#       (REQUIRED -- recipe fails if missing; create the worktree with
#       `git -C ~/project/forever-claude-template worktree add` before
#       running minds-start).
#   MINDS_WORKSPACE_BRANCH  = the FCT worktree's current branch.
#   MINDS_WORKSPACE_NAME    = "mindtest".
# Override agent_name / branch via positional args:
#   just minds-start agent_name=foo branch=some-branch
# Refuses to start if another minds-start is already running in this
# worktree (PID file under /tmp keyed by worktree path). Use `just
# minds-stop` to kill the running instance first.
minds-start agent_name="mindtest" branch="":
    #!/bin/bash
    set -ueo pipefail
    if [ -z "${MINDS_ROOT_NAME:-}" ]; then
        echo "error: MINDS_ROOT_NAME is not set." >&2
        echo "       Add \`export MINDS_ROOT_NAME=devminds\` (or your chosen root name) to your ~/.bashrc" >&2
        echo "       so that minds bootstrap can derive MNGR_HOST_DIR / MNGR_PREFIX correctly." >&2
        echo "       Without an explicit MINDS_ROOT_NAME, an inherited MNGR_HOST_DIR from the parent" >&2
        echo "       shell wins and minds reads a different mngr settings.toml than its bootstrap writes." >&2
        exit 2
    fi
    pid_file="/tmp/minds-start-$(echo -n "$PWD" | sha1sum | cut -c1-12).pid"
    if [ -f "$pid_file" ]; then
        existing=$(cat "$pid_file" 2>/dev/null || echo "")
        if [ -n "$existing" ] && kill -0 "$existing" 2>/dev/null; then
            echo "error: minds-start is already running in this worktree (pid=$existing)" >&2
            echo "       run \`just minds-stop\` first." >&2
            exit 2
        fi
        rm -f "$pid_file"
    fi
    fct_wt="$(pwd)/.external_worktrees/forever-claude-template"
    if [ ! -e "$fct_wt/.git" ]; then
        echo "error: no FCT worktree at $fct_wt" >&2
        echo "       run \`git -C ~/project/forever-claude-template worktree add -b <branch> $fct_wt <base>\`" >&2
        echo "       (e.g. base = josh/start-minds) before re-running minds-start." >&2
        exit 2
    fi
    if [ -f .env ]; then
        set -a
        . .env
        set +a
    fi
    export MINDS_WORKSPACE_GIT_URL="$fct_wt"
    if [ -n "{{branch}}" ]; then
        export MINDS_WORKSPACE_BRANCH="{{branch}}"
    else
        export MINDS_WORKSPACE_BRANCH="$(git -C "$fct_wt" rev-parse --abbrev-ref HEAD)"
    fi
    export MINDS_WORKSPACE_NAME="{{agent_name}}"
    echo "MINDS_WORKSPACE_GIT_URL=$MINDS_WORKSPACE_GIT_URL"
    echo "MINDS_WORKSPACE_NAME=$MINDS_WORKSPACE_NAME"
    echo "MINDS_WORKSPACE_BRANCH=$MINDS_WORKSPACE_BRANCH"
    echo "$$" > "$pid_file"
    trap 'rm -f "$pid_file"' EXIT
    cd apps/minds && pnpm start

# Stop the minds desktop client started in this worktree by `just minds-start`.
#
# Strategy: walk the recipe shell's process tree, find Electron's main
# process, and SIGTERM that specifically. The Electron main process has a
# `process.on('SIGTERM', () => app.quit())` handler (apps/minds/electron/
# main.js) that triggers the `before-quit` chain -- which already
# SIGTERMs the python backend and waits for uvicorn's graceful exit.
# After electron exits cleanly: its zygotes / utility children die via
# PR_SET_DEATHSIG, the python backend's grandparent-death watcher (which
# already exists in apps/minds/imbue/minds/cli/run.py) sees electron die
# and exits cleanly itself, pnpm / node / sh / the recipe shell exit as
# their children terminate. Whole tree gone in <2s typically.
#
# Why we don't just SIGTERM the recipe shell (the PID stored in pid_file):
#   `kill <pid>` signals only that PID. Bash's default SIGTERM behavior is
#   to exit cleanly without forwarding the signal to its children, so
#   children become orphans and survive indefinitely. We saw this
#   empirically -- the previous version of this recipe always fell through
#   to the SIGKILL fallback because nothing was telling electron to quit.
#
# Why not kill the recipe shell's process group with `kill -- -<pgid>`:
#   In this stack the PGID leader is `just` itself (one level above the
#   recipe shell), and the group cleanly contains only this minds
#   invocation. That's safe-by-inspection here but brittle as a general
#   rule -- nothing prevents some future change to the harness from
#   placing unrelated processes in the same PGID. PID-by-PID via pstree
#   can't accidentally touch anything outside the tree.
#
# Idempotent (no-op if nothing running). Falls back to SIGTERM-the-recipe
# if electron hasn't reached its main process yet (rare startup race), and
# to SIGKILLing specific surviving PIDs if the graceful path doesn't
# finish within 10s.
minds-stop:
    #!/bin/bash
    set -ueo pipefail
    pid_file="/tmp/minds-start-$(echo -n "$PWD" | sha1sum | cut -c1-12).pid"
    if [ ! -f "$pid_file" ]; then
        echo "no PID file at $pid_file -- nothing to stop"
        exit 0
    fi
    pid=$(cat "$pid_file")
    if [ -z "$pid" ] || ! kill -0 "$pid" 2>/dev/null; then
        echo "PID $pid in $pid_file is not running -- removing stale file"
        rm -f "$pid_file"
        exit 0
    fi
    # Snapshot the full descendant tree. pstree -p -T walks PPID links and
    # gives PIDs in flat form. We'll use this both to identify electron's
    # main process and to verify the whole tree exits.
    descendants=$(pstree -p -T "$pid" 2>/dev/null | grep -oE '\([0-9]+\)' | tr -d '()' | sort -u)
    # Locate Electron's main process: the descendant whose cmd contains the
    # electron binary path and is NOT a `--type=zygote` / `--type=utility`
    # / `--type=...` subprocess. There's exactly one such process per
    # session (the rest are renderer / GPU / network helpers it spawned).
    electron_main_pid=""
    for d in $descendants; do
        cmd=$(ps -o cmd= -p "$d" 2>/dev/null || true)
        if [[ "$cmd" == *"node_modules/electron/dist/electron "* && "$cmd" != *"--type="* ]]; then
            electron_main_pid="$d"
            break
        fi
    done
    if [ -n "$electron_main_pid" ]; then
        echo "Stopping minds (recipe=$pid, electron=$electron_main_pid) via clean shutdown"
        kill -TERM "$electron_main_pid"
    else
        # Pre-electron startup race: electron hasn't been exec'd yet. Fall
        # back to the recipe shell, which at least kills the bash sitting
        # in `pnpm install` / similar.
        echo "Stopping minds-start (pid=$pid, electron not yet spawned)"
        kill -TERM "$pid"
    fi
    # Wait up to 10s for the whole tree to exit.
    for i in $(seq 1 10); do
        still_alive=""
        for descendant in $descendants; do
            if kill -0 "$descendant" 2>/dev/null; then
                still_alive="$still_alive $descendant"
            fi
        done
        if [ -z "$still_alive" ]; then
            rm -f "$pid_file"
            exit 0
        fi
        sleep 1
    done
    # Force-kill anything that survived the grace period. Each kill targets
    # a specific PID we observed under the recipe shell -- never a broad
    # pgrep-style match.
    echo "Tree did not exit after 10s SIGTERM grace; force-killing leftovers:$still_alive"
    for descendant in $still_alive; do
        kill -9 "$descendant" 2>/dev/null || true
    done
    rm -f "$pid_file"

# Build the minds desktop client distributable (slow; uses todesktop).
minds-build:
    cd apps/minds && pnpm build

# Sync this repo's mngr changes (and the FCT worktree's template state)
# into a running Docker agent's container, then restart the agent and the
# desktop client. Wraps apps/minds/scripts/propagate_changes by auto-
# discovering the agent's Docker SSH port (via `docker port`) and the
# minds-side SSH key (under MNGR_HOST_DIR's profiles/.../docker/.../keys/).
# Defaults MNGR_HOST_DIR to ~/.minds/mngr (production minds); pass
# mngr_host_dir=$HOME/.devminds/mngr if you're on a dev profile.
propagate-changes agent_name mngr_host_dir="$HOME/.minds/mngr":
    #!/bin/bash
    set -ueo pipefail
    agent_name="{{agent_name}}"
    mngr_host_dir="{{mngr_host_dir}}"
    container_name="mngr-${agent_name}-host"
    if ! docker inspect "$container_name" >/dev/null 2>&1; then
        echo "error: no docker container named '$container_name'" >&2
        echo "       run \`docker ps\` to see running containers" >&2
        exit 2
    fi
    port_mapping=$(docker port "$container_name" 22/tcp 2>/dev/null | head -1)
    if [ -z "$port_mapping" ]; then
        echo "error: container $container_name has no host port mapping for 22/tcp" >&2
        exit 2
    fi
    port="${port_mapping##*:}"
    keys=$(find "$mngr_host_dir/profiles" -path "*/docker/*/keys/docker_ssh_key" 2>/dev/null || true)
    if [ -z "$keys" ]; then
        echo "error: no docker_ssh_key found under $mngr_host_dir/profiles" >&2
        echo "       try mngr_host_dir=\$HOME/.devminds/mngr if you're on a dev profile," >&2
        echo "       or pass mngr_host_dir=<custom path>." >&2
        exit 2
    fi
    key_count=$(echo "$keys" | wc -l)
    if [ "$key_count" -gt 1 ]; then
        echo "error: multiple docker_ssh_key files found under $mngr_host_dir/profiles:" >&2
        echo "$keys" >&2
        echo "       narrow with mngr_host_dir=<more specific path>." >&2
        exit 2
    fi
    key="$keys"
    echo "Propagating changes to $agent_name (container=$container_name, port=$port, key=$key)"
    apps/minds/scripts/propagate_changes \
        --agent "$agent_name" \
        --user root --host 127.0.0.1 --port "$port" --key "$key"

# Create a Cloudflare tunnel for the named agent's system_interface
# service: locks the tunnel to the active imbue_cloud account, injects
# the cloudflared token into the agent (via mngr exec), and registers
# system_interface at http://localhost:8000 on the tunnel. Prints the
# resulting public hostname. Idempotent: tunnels create returns the
# existing tunnel if one already exists; service add no-ops if the same
# DNS+target is already registered.
# Forward system_interface for a minds-profile agent.
forward-minds-system-interface agent_name: (_forward-system-interface agent_name "$HOME/.minds/mngr" "minds-")

# Same as forward-minds-system-interface but for the dev (devminds) profile.
forward-devminds-system-interface agent_name: (_forward-system-interface agent_name "$HOME/.devminds/mngr" "devminds-")

[private]
_forward-system-interface agent_name mngr_host_dir mngr_prefix:
    #!/bin/bash
    set -ueo pipefail
    export MNGR_HOST_DIR="{{mngr_host_dir}}"
    export MNGR_PREFIX="{{mngr_prefix}}"
    AGENT_NAME="{{agent_name}}"

    # Resolve agent name to its full agent_id from local mngr state. The
    # tunnel layer truncates "agent-<hex>" to the first 16 hex chars for
    # hostname uniqueness, so the full id is what we want here -- not the
    # short name (which would let two agents with the same name across
    # different hosts collide in the tunnel namespace).
    AGENT_ID=$(uv run mngr list --format jsonl 2>/dev/null \
        | jq -r --arg n "$AGENT_NAME" 'select(.resource_type == "agent" and .name == $n) | .id' \
        | head -1)
    if [ -z "$AGENT_ID" ]; then
        echo "error: no agent named '$AGENT_NAME' found via 'mngr list' under MNGR_HOST_DIR=$MNGR_HOST_DIR" >&2
        exit 1
    fi

    EMAIL=$(uv run mngr imbue_cloud auth list \
        | jq -r '.[] | select(.is_active) | .email')
    if [ -z "$EMAIL" ]; then
        echo "error: no active imbue_cloud account; run 'mngr imbue_cloud auth signin' first" >&2
        exit 1
    fi

    TUNNEL_JSON=$(uv run mngr imbue_cloud tunnels create "$AGENT_ID" \
        --account "$EMAIL" \
        --policy "$(jq -nc --arg e "$EMAIL" '{emails:[$e]}')")
    TUNNEL_NAME=$(jq -r '.tunnel_name' <<<"$TUNNEL_JSON")
    TOKEN=$(jq -r '.token' <<<"$TUNNEL_JSON")
    if [ -z "$TUNNEL_NAME" ] || [ "$TOKEN" = "null" ]; then
        echo "error: tunnels create did not return a usable tunnel/token:" >&2
        echo "$TUNNEL_JSON" >&2
        exit 1
    fi

    # Inject the token where the agent's cloudflare-tunnel service
    # (libs/cloudflare_tunnel/.../runner.py) watches for it. Strip any
    # existing CLOUDFLARE_TUNNEL_TOKEN line first so we don't keep two
    # copies, then atomic-rename so the watcher never observes a
    # half-written file. CF tokens are base64url-y, so single-quoting
    # the value is safe.
    uv run mngr exec "$AGENT_ID" \
        "mkdir -p runtime && { [ -f runtime/secrets ] && grep -Ev '^export[[:space:]]+CLOUDFLARE_TUNNEL_TOKEN=' runtime/secrets || true; printf 'export CLOUDFLARE_TUNNEL_TOKEN=%s\n' '$TOKEN'; } > runtime/secrets.tmp && mv runtime/secrets.tmp runtime/secrets"

    URL=$(uv run mngr imbue_cloud tunnels services add \
        "$TUNNEL_NAME" system_interface http://localhost:8000 \
        | jq -r .hostname)
    if [ -z "$URL" ] || [ "$URL" = "null" ]; then
        echo "error: services add did not return a hostname" >&2
        exit 1
    fi

    echo
    echo "Forwarded system_interface for $AGENT_NAME ($AGENT_ID)"
    echo "  URL:    https://$URL/"
    echo "  Tunnel: $TUNNEL_NAME (locked to $EMAIL)"

# Spin up a new PRIVATE personal GitHub repo as a full-history copy of
# imbue-ai/forever-claude-template's main. Clones into
# <parent_dir>/<repo_name> (default parent: $HOME/project), creates the
# repo under whichever account `gh` is authenticated as, pushes main,
# and prints a pre-filled URL for a fine-grained PAT scoped to it. See
# .claude/skills/new-forever-claude-clone/SKILL.md for the rationale.
# Create a new private personal repo from forever-claude-template.
create-new-mind-repo repo_name parent_dir="$HOME/project":
    #!/bin/bash
    set -ueo pipefail
    repo="{{repo_name}}"
    parent="{{parent_dir}}"
    fct="$HOME/project/forever-claude-template"

    if ! command -v gh >/dev/null 2>&1; then
        echo "error: gh CLI not found on PATH" >&2; exit 2
    fi
    if ! gh auth status >/dev/null 2>&1; then
        echo "error: gh is not authenticated; run 'gh auth login' first" >&2; exit 2
    fi
    owner=$(gh api user --jq .login)
    if [ -z "$owner" ]; then
        echo "error: could not determine GitHub username from 'gh api user'" >&2; exit 2
    fi
    if [ ! -d "$fct/.git" ]; then
        echo "error: $fct is not a git repo (skill expects forever-claude-template here)" >&2; exit 2
    fi
    if [ ! -d "$parent" ]; then
        echo "error: parent directory '$parent' does not exist" >&2; exit 2
    fi
    target="$parent/$repo"
    if [ -e "$target" ]; then
        echo "error: $target already exists; refusing to overwrite" >&2; exit 2
    fi
    if gh repo view "$owner/$repo" >/dev/null 2>&1; then
        echo "error: github repo $owner/$repo already exists; refusing to push into it" >&2; exit 2
    fi

    cd "$parent"
    git clone git@github.com:imbue-ai/forever-claude-template.git "$repo"
    cd "$repo"
    git checkout main
    git remote remove origin
    gh repo create "$owner/$repo" --private --source=. --remote=origin --push

    commits=$(git rev-list --count HEAD)
    pat_url="https://github.com/settings/personal-access-tokens/new?name=${repo}&description=${repo}%20token&target_name=${owner}&expires_in=none&contents=write&metadata=read&pull_requests=write&issues=write&workflows=write"

    echo
    echo "Created $owner/$repo"
    echo "  Web:    https://github.com/$owner/$repo"
    echo "  Clone:  git@github.com:$owner/$repo.git"
    echo "  Local:  $target"
    echo "  Commits: $commits"
    echo
    echo "Create a fine-grained PAT scoped to this repo (no expiration, contents/PR/issues/workflows write):"
    echo "  $pat_url"
    echo
    echo "After opening the link: GitHub does not accept repository selection via URL params,"
    echo "so under 'Repository access' choose 'Only select repositories' and add $owner/$repo."
    echo

    if [ ! -t 0 ]; then
        echo "(stdin is not a TTY; skipping interactive token prompt and LiteLLM key creation -- create .env manually if needed)"
        exit 0
    fi

    echo "Paste the generated PAT here (input hidden), or press Enter to skip GH_TOKEN:"
    gh_token=""
    read -r -s gh_token || gh_token=""
    echo

    # Mint a LiteLLM virtual key for this repo and pull ANTHROPIC_API_KEY +
    # ANTHROPIC_BASE_URL out of the JSON response (see
    # libs/mngr_imbue_cloud/.../cli/keys.py:create_key -> emits {key, base_url}).
    # Failures here are non-fatal: the GitHub repo is already created and
    # pushed at this point, and the user can always create a key manually
    # later via `mngr imbue_cloud keys litellm create`.
    api_key=""
    base_url=""
    echo "Creating LiteLLM virtual key (alias: $repo)..."
    litellm_output=""
    if litellm_output=$(uv run --project {{justfile_directory()}} mngr imbue_cloud keys litellm create --alias "$repo" 2>&1); then
        api_key=$(jq -r '.key // empty' <<<"$litellm_output" 2>/dev/null || echo "")
        base_url=$(jq -r '.base_url // empty' <<<"$litellm_output" 2>/dev/null || echo "")
        if [ -z "$api_key" ] || [ -z "$base_url" ]; then
            echo "warning: LiteLLM create returned unexpected output; skipping ANTHROPIC_* vars" >&2
            echo "$litellm_output" >&2
            api_key=""
            base_url=""
        fi
    else
        echo "warning: 'mngr imbue_cloud keys litellm create' failed; skipping ANTHROPIC_* vars" >&2
        echo "$litellm_output" >&2
        api_key=""
        base_url=""
    fi

    env_file="$target/.env"
    if [ -z "$gh_token" ] && [ -z "$api_key" ]; then
        echo "Nothing collected (no GH PAT, no LiteLLM key); skipped .env"
        exit 0
    fi
    : > "$env_file"
    chmod 600 "$env_file"
    [ -n "$gh_token" ] && printf 'export GH_TOKEN=%s\n' "$gh_token" >> "$env_file"
    [ -n "$api_key" ] && printf 'export ANTHROPIC_API_KEY=%s\n' "$api_key" >> "$env_file"
    [ -n "$base_url" ] && printf 'export ANTHROPIC_BASE_URL=%s\n' "$base_url" >> "$env_file"
    echo "Wrote $env_file (mode 600)"

# Destroy and remove every host in the pool with status='released'.
# Sources .minds/<env>/neon.sh for DATABASE_URL.
cleanup-pool-hosts env="production":
    #!/bin/bash
    set -ueo pipefail
    set -a
    . .minds/{{env}}/neon.sh
    set +a
    uv run python apps/remote_service_connector/scripts/cleanup_released_hosts.py \
        --database-url "$DATABASE_URL"
