"""``minds_deployment`` test: re-deploying advances the live Modal app version.

The cheapest possible "redeploy actually deploys" assertion: the
``ephemeral_env`` fixture has already done v1's deploy and yielded a
handle; this test captures v1's ``deploy_id`` from ``/version``,
triggers a second ``minds env deploy`` against the same env (which
mints a fresh ``MINDS_DEPLOY_ID`` automatically), and asserts the
live version id moved forward.
"""

import subprocess
from pathlib import Path

import httpx
import pytest

from imbue.minds.deployment_tests.data_types import EphemeralEnvHandle
from imbue.minds.deployment_tests.helpers import build_minds_env_subprocess_env

# ``minds env deploy`` validates that it's invoked from inside the
# monorepo. Pytest changes cwd to a tmpdir per test, so we pin the
# subprocess's cwd to the repo root explicitly. Same rationale as
# conftest._REPO_ROOT_FOR_SUBPROCESS.
_REPO_ROOT = Path(__file__).resolve().parents[3]

pytestmark = pytest.mark.minds_deployment


# Generous per-test timeout: v2 deploy adds another ~3 min on top of
# ephemeral_env's v1 deploy + final destroy. The pyproject-wide 10s
# default is sized for unit tests.
_TEST_TIMEOUT_SECONDS = 15 * 60

_REQUEST_TIMEOUT_SECONDS = 30.0
_REDEPLOY_TIMEOUT_SECONDS = 10 * 60


@pytest.mark.timeout(_TEST_TIMEOUT_SECONDS)
def test_deploy_new_version(ephemeral_env: EphemeralEnvHandle) -> None:
    """Deploy twice; assert the connector's live ``/version`` reports a new ``deploy_id``.

    Defensive preamble: the ``ephemeral_env`` fixture has already
    awaited a healthy v1 deploy (via ``await_apps_healthy`` inside the
    deploy CLI), so the env is reachable when we enter the test body.

    Flow:
    1. ``GET <connector_url>/version`` → record ``v1_deploy_id``.
    2. ``uv run minds env deploy`` (subprocess, activation env vars
       inherited via the fixture's helper) against the same env.
       ``MINDS_DEPLOY_ID`` is regenerated by the orchestration so no
       arg change is needed.
    3. ``GET <connector_url>/version`` → record ``v2_deploy_id``.
    4. Assert ``v2_deploy_id != v1_deploy_id`` AND lex-sorts strictly
       greater (the deploy id format is lex-sortable per
       ``secret_lifecycle.DeployId``).
    """
    connector_url = str(ephemeral_env.connector_url).rstrip("/")
    with httpx.Client(timeout=_REQUEST_TIMEOUT_SECONDS) as client:
        version_v1 = client.get(f"{connector_url}/version")
    assert version_v1.status_code == 200, version_v1.text
    v1_deploy_id = version_v1.json()["deploy_id"]
    assert v1_deploy_id, version_v1.json()

    # Trigger the second deploy. ``build_minds_env_subprocess_env`` from
    # the helpers module mirrors what ``minds env activate <name>``
    # exports so the subprocess targets ``ephemeral_env.name``.
    sub_env = build_minds_env_subprocess_env(ephemeral_env.name)
    completed = subprocess.run(
        ["uv", "run", "minds", "env", "deploy"],
        env=sub_env,
        cwd=str(_REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=_REDEPLOY_TIMEOUT_SECONDS,
        check=False,
    )
    assert completed.returncode == 0, (
        f"Second `minds env deploy` for {ephemeral_env.name!r} exited {completed.returncode}.\n"
        f"--- stdout ---\n{completed.stdout}\n--- stderr ---\n{completed.stderr}"
    )

    with httpx.Client(timeout=_REQUEST_TIMEOUT_SECONDS) as client:
        version_v2 = client.get(f"{connector_url}/version")
    assert version_v2.status_code == 200, version_v2.text
    v2_deploy_id = version_v2.json()["deploy_id"]
    assert v2_deploy_id, version_v2.json()
    assert v2_deploy_id != v1_deploy_id, (v1_deploy_id, v2_deploy_id)
    assert v2_deploy_id > v1_deploy_id, (
        "Deploy id format is lex-sortable (YYYYMMDDTHHMMSSZ); v2 should sort strictly greater than v1.",
        v1_deploy_id,
        v2_deploy_id,
    )

    # ephemeral_env fixture teardown will destroy the env unconditionally.
