#!/usr/bin/env node
// Regenerate src/generated/ from the server's pydantic JSON Schema.
//
// Pipeline: `uv run python apps/minds/scripts/generate_ui_schema.py` (run from
// the repo root) writes the consolidated JSON Schema to stdout; we feed it to
// json-schema-to-typescript and write src/generated/ui.ts. Degrades with a
// clear message while the schema script does not exist yet (it lands with the
// server foundation).

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const frontendDir = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = resolve(frontendDir, "..", "..", "..");
const schemaScript = resolve(repoRoot, "apps", "minds", "scripts", "generate_ui_schema.py");

if (!existsSync(schemaScript)) {
  console.error(
    `generate-types: ${schemaScript} does not exist yet (it lands with the server foundation); skipping.`,
  );
  process.exit(0);
}

const schemaJson = execFileSync("uv", ["run", "python", schemaScript], {
  cwd: repoRoot,
  encoding: "utf-8",
  maxBuffer: 64 * 1024 * 1024,
});

const { compile } = await import("json-schema-to-typescript");
const schema = JSON.parse(schemaJson);
const banner =
  "/* Generated by `pnpm generate` from the server's pydantic JSON Schema. DO NOT EDIT. */\n\n";
const ts = await compile(schema, schema.title ?? "UiSchema", {
  bannerComment: banner.trimEnd(),
  additionalProperties: false,
});
const outDir = resolve(frontendDir, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "ui.ts"), ts);
console.log("generate-types: wrote src/generated/ui.ts");
