"""Tests for the TROUBLESHOOTING tutorial section.

The blocks in this section are short diagnostic commands prefixed with
"auto-generated by Claude, remove when a human has sanctioned this" -- the
matcher treats them as real blocks, so each gets a thin test that just
verifies the command runs cleanly against a real my-task agent.
"""

import json

import pytest

from imbue.mngr.e2e.conftest import E2eSession
from imbue.skitwright.expect import expect


def _create_my_task(e2e: E2eSession, sleep_value: int) -> None:
    expect(
        e2e.run(
            f"mngr create my-task --type command --no-ensure-clean --no-connect -- sleep {sleep_value}",
            comment=f"create my-task (sleep {sleep_value})",
        )
    ).to_succeed()


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
def test_troubleshoot_check_agent_state(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # check if the agent exists and its current state
        mngr list --fields "name,state,host.provider,host.name"
    """)
    _create_my_task(e2e, 101020)
    result = e2e.run(
        'mngr list --fields "name,state,host.provider,host.name"',
        comment="check if the agent exists and its current state",
    )
    expect(result).to_succeed()
    # The agent we just created must show up as a row rendering exactly the
    # requested fields: its name, some state, the local provider, and the
    # localhost host name (state is left as \S+ to avoid depending on timing).
    expect(result.stdout).to_match(r"my-task\s+\S+\s+local\s+localhost")


# This test creates a local command-type agent and reads its events. Creating the
# agent exercises tmux (the agent's session) and rsync (same-host workspace sync),
# but nothing here invokes modal -- the agent is local and `mngr event` reads it
# directly. The modal mark is intentionally absent so the resource guard does not
# fail the test for a superfluous mark.
@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
def test_troubleshoot_recent_events(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # view recent events to understand what happened
        mngr event my-task --tail 20
    """)
    _create_my_task(e2e, 101021)
    result = e2e.run("mngr event my-task --tail 20", comment="view recent events")
    expect(result).to_succeed()
    # Events are printed as JSONL: every non-blank line must be a JSON object
    # carrying the guaranteed envelope fields. A freshly-created command agent
    # may legitimately have no events yet, so an empty result is acceptable --
    # but any line that is present must satisfy the documented contract.
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        event = json.loads(line)
        assert isinstance(event, dict), f"event line is not a JSON object: {line!r}"
        for field in ("event_id", "timestamp", "source", "type"):
            assert field in event, f"event missing guaranteed field {field!r}: {line!r}"


# Unhappy-path companion for the same tutorial block: when troubleshooting, the
# agent name is often wrong or the agent is already gone. `mngr event` must fail
# clearly rather than hang or print an empty success. This test creates no agent,
# so it touches no guarded resource (tmux/rsync/modal) and carries only @release.
@pytest.mark.release
def test_troubleshoot_recent_events_missing_agent(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # view recent events to understand what happened
        mngr event my-task --tail 20
    """)
    result = e2e.run("mngr event no-such-task --tail 20", comment="view recent events for a missing agent")
    expect(result).to_fail()
    expect(result.stderr).to_contain("Could not find agent")


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
def test_troubleshoot_follow_events(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # follow events in real time while reproducing an issue
        mngr event my-task --follow
    """)
    _create_my_task(e2e, 101022)
    # `mngr event --follow` blocks forever (like `tail -f`); `timeout` stands in
    # for the Ctrl-C a user would press. A healthy follow is still streaming when
    # the timeout fires, so `timeout` kills it and exits 124. A follow that
    # crashed during startup (e.g. failed to resolve the agent) would have exited
    # earlier with a different code, so asserting 124 confirms it was actively
    # following rather than that the command merely ran.
    expect(
        e2e.run("timeout 1 mngr event my-task --follow", comment="follow events while reproducing")
    ).to_have_exit_code(124)


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
def test_troubleshoot_transcript_for_errors(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # check the agent's transcript for error messages
        mngr transcript my-task --tail 10
    """)
    # The tutorial's `my-task` is a conversational (e.g. claude) agent. Here we
    # substitute a lightweight `command` agent (the standard e2e substitution to
    # avoid claude startup cost and credentials). Command agents have no
    # conversation, so `mngr transcript` fails fast with a clear, type-specific
    # diagnostic instead of a misleading "no transcript yet" message -- itself a
    # useful troubleshooting signal. We assert on that documented behavior.
    _create_my_task(e2e, 101023)
    result = e2e.run("mngr transcript my-task --tail 10", comment="check transcript for error messages")
    expect(result).to_fail()
    expect(result.stderr).to_contain("does not produce a common transcript")


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
def test_troubleshoot_host_diagnostics(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # run commands on the host to diagnose issues
        mngr exec my-task "cat /var/log/syslog | tail -20"
        mngr exec my-task "ps aux"
        mngr exec my-task "df -h"
    """)
    _create_my_task(e2e, 101024)
    # /var/log/syslog may not exist (e.g. on macOS hosts); allow failure for
    # the cat and require only that mngr forwards the command to the host.
    e2e.run('mngr exec my-task "cat /var/log/syslog | tail -20" || true', comment="cat syslog")
    # ps aux must run on the host and list the sleep process backing my-task,
    # proving the command ran on the agent's host rather than being misparsed.
    ps_result = e2e.run('mngr exec my-task "ps aux"', comment="ps aux")
    expect(ps_result).to_succeed()
    assert "sleep 101024" in ps_result.stdout, f"expected the agent's sleep process in ps output: {ps_result.stdout}"
    # df -h must report a filesystem table; the header line is always present.
    df_result = e2e.run('mngr exec my-task "df -h"', comment="df -h")
    expect(df_result).to_succeed()
    assert "Filesystem" in df_result.stdout, f"expected a df header line in output: {df_result.stdout}"


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.timeout(120)
def test_troubleshoot_stop_restart(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # if an agent is stuck, try stopping and restarting it
        mngr stop my-task
        mngr start my-task --connect
    """)
    _create_my_task(e2e, 101025)
    # The agent's workload (the `sleep` command) is running once created. The
    # `[s]leep` bracket trick keeps pgrep from matching the exec command itself.
    expect(
        e2e.run("mngr exec my-task \"pgrep -f '[s]leep 101025'\"", comment="workload running before stop")
    ).to_succeed()
    expect(e2e.run("mngr stop my-task", comment="stop the agent")).to_succeed()
    # Stopping kills the workload. Use --no-start so the check observes the
    # stopped state instead of silently restarting the agent.
    expect(
        e2e.run("mngr exec my-task --no-start \"pgrep -f '[s]leep 101025'\"", comment="workload gone after stop")
    ).to_fail()
    expect(e2e.run("mngr start my-task --connect", comment="start and reconnect")).to_succeed()
    # Restarting relaunches the workload.
    expect(
        e2e.run("mngr exec my-task \"pgrep -f '[s]leep 101025'\"", comment="workload running after restart")
    ).to_succeed()


@pytest.mark.release
@pytest.mark.modal
@pytest.mark.rsync
@pytest.mark.timeout(240)
def test_troubleshoot_destroy_and_recreate_modal(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # if a host is in a bad state, destroy and recreate
        mngr destroy my-task --force
        mngr create my-task --provider modal
    """)
    # The tutorial block omits --type because a real user has a default agent
    # type configured; the test environment has none, so substitute --type
    # command + sleep (matching the other tutorial tests) for a fast modal host.
    expect(
        e2e.run(
            "mngr create my-task --provider modal --type command --no-connect --no-ensure-clean -- sleep 101026",
            comment="create modal my-task to destroy",
            timeout=180.0,
        )
    ).to_succeed()
    # The agent should now exist on a modal host before we destroy it.
    before = e2e.run('mngr list --fields "name,host.provider"', comment="confirm the agent exists")
    expect(before).to_succeed()
    expect(before.stdout).to_contain("my-task")
    expect(before.stdout).to_contain("modal")

    expect(e2e.run("mngr destroy my-task --force", comment="destroy")).to_succeed()
    # Destroying with --force must actually remove the agent, not just exit 0.
    after_destroy = e2e.run('mngr list --fields "name"', comment="confirm the agent is gone")
    expect(after_destroy).to_succeed()
    expect(after_destroy.stdout).not_to_contain("my-task")

    expect(
        e2e.run(
            "mngr create my-task --provider modal --type command --no-connect --no-ensure-clean -- sleep 101026",
            comment="recreate",
            timeout=180.0,
        )
    ).to_succeed()
    # Recreate must bring back a fresh modal agent under the same name.
    after_recreate = e2e.run('mngr list --fields "name,host.provider"', comment="confirm the agent was recreated")
    expect(after_recreate).to_succeed()
    expect(after_recreate.stdout).to_contain("my-task")
    expect(after_recreate.stdout).to_contain("modal")


@pytest.mark.release
@pytest.mark.modal
@pytest.mark.rsync
@pytest.mark.timeout(300)
def test_troubleshoot_gc_dry_run_then_gc(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # garbage collect to clean up any orphaned resources
        mngr gc --dry-run
        mngr gc
    """)
    # gc only reaches the Modal API once a Modal environment actually exists,
    # which happens the first time an agent is created there. Create a live
    # Modal agent first so gc has real provider state to scan -- otherwise gc
    # short-circuits (no Modal state yet) and never exercises Modal at all.
    expect(
        e2e.run(
            "mngr create my-task --type command --provider modal --no-ensure-clean --no-connect -- sleep 101030",
            comment="create a live modal agent so gc has provider state to scan",
            timeout=180.0,
        )
    ).to_succeed()
    # gc scans every configured provider (including the Modal API), so both the
    # dry run and the real run can take well over the default pytest timeout.
    expect(e2e.run("mngr gc --dry-run", comment="dry-run gc", timeout=120.0)).to_succeed()
    expect(e2e.run("mngr gc", comment="run gc", timeout=120.0)).to_succeed()
    # gc must never destroy a host that still has a live agent: the my-task
    # agent created above must survive both the dry run and the real run.
    list_result = e2e.run("mngr list --fields name", comment="confirm gc kept the live agent")
    expect(list_result).to_succeed()
    expect(list_result.stdout).to_contain("my-task")
