"""Tests for the TROUBLESHOOTING tutorial section.

The blocks in this section are short diagnostic commands prefixed with
"auto-generated by Claude, remove when a human has sanctioned this" -- the
matcher treats them as real blocks, so each gets a thin test that runs the
command against a real my-task agent. Most just verify the command runs
cleanly; the transcript block instead verifies a clear diagnostic, because a
lightweight `command` agent deliberately has no common transcript.
"""

import json

import pytest

from imbue.mngr.e2e.conftest import E2eSession
from imbue.skitwright.expect import expect


def _create_my_task(e2e: E2eSession, sleep_value: int) -> None:
    expect(
        e2e.run(
            f"mngr create my-task --type command --no-ensure-clean --no-connect -- sleep {sleep_value}",
            comment=f"create my-task (sleep {sleep_value})",
        )
    ).to_succeed()


@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.timeout(120)
def test_troubleshoot_check_agent_state(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # check if the agent exists and its current state
        mngr list --fields "name,state,host.provider,host.name"
    """)
    _create_my_task(e2e, 101020)
    result = e2e.run(
        'mngr list --fields "name,state,host.provider,host.name"',
        comment="check if the agent exists and its current state",
    )
    expect(result).to_succeed()
    # The diagnostic is meant to surface the agent and its resolved host info:
    # the just-created agent must appear with its provider (local in this fixture).
    expect(result.stdout).to_contain("my-task")
    expect(result.stdout).to_contain("local")


@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.timeout(120)
def test_troubleshoot_recent_events(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # view recent events to understand what happened
        mngr event my-task --tail 20
    """)
    _create_my_task(e2e, 101021)
    result = e2e.run("mngr event my-task --tail 20", comment="view recent events")
    expect(result).to_succeed()
    # Events are emitted as JSONL, one event record per line. A freshly created
    # command agent may have no agent-level events yet (so the output can be
    # empty), but whatever is printed must be well-formed JSONL -- that is the
    # contract a human relies on when piping `mngr event` into other tools.
    event_records = [json.loads(line) for line in result.stdout.splitlines() if line.strip()]
    assert all(isinstance(record, dict) for record in event_records), (
        f"Expected every event line to be a JSON object, got: {result.stdout!r}"
    )


@pytest.mark.release
@pytest.mark.timeout(120)
def test_troubleshoot_recent_events_missing_agent(e2e: E2eSession) -> None:
    # Unhappy path for the same tutorial block: a human who typos the agent
    # name (or queries an agent that no longer exists) should get a clear
    # "could not find" error rather than empty output or a crash. Resolving an
    # unknown name forces a full provider scan, but no host is provisioned, so
    # this exercises no tmux/rsync/modal resources.
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # view recent events to understand what happened
        mngr event my-task --tail 20
    """)
    result = e2e.run("mngr event no-such-agent-zzz --tail 20", comment="view events for a missing agent")
    expect(result).to_fail()
    expect(result.stderr).to_contain("Could not find agent")
    # The diagnostic must name the specific agent the human typed (not a generic
    # message), so a typo is immediately obvious from the error alone.
    expect(result.stderr).to_contain("no-such-agent-zzz")
    # A missing target is a clean lookup failure, not a crash: no traceback should
    # leak to the human, who would otherwise mistake a typo for a tool bug.
    expect(result.stderr).not_to_contain("Traceback")


@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.timeout(120)
def test_troubleshoot_follow_events(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # follow events in real time while reproducing an issue
        mngr event my-task --follow
    """)
    _create_my_task(e2e, 101022)
    # --follow streams forever until interrupted, so bound it with `timeout`.
    # The window must exceed mngr's cold-start cost so the command actually
    # reaches and stays in the follow loop rather than being killed mid-startup.
    # A clean follow run gets killed by `timeout` and exits 124; any earlier
    # exit (e.g. a crash or an error resolving the target) yields a different
    # code, which this assertion would catch -- unlike a `|| true` guard.
    follow_result = e2e.run("timeout 12 mngr event my-task --follow", comment="follow events while reproducing")
    expect(follow_result).to_have_exit_code(124)
    # Beyond surviving until `timeout` fires, the follow stream must honor the
    # same JSONL contract as `mngr event --tail`: it first prints any existing
    # backlog, then streams new events, one JSON object per line. A freshly
    # created command agent may have no events yet (so the output can be empty),
    # but anything it does print must be well-formed JSONL -- otherwise piping
    # `mngr event --follow` into other tools would break.
    event_records = [json.loads(line) for line in follow_result.stdout.splitlines() if line.strip()]
    assert all(isinstance(record, dict) for record in event_records), (
        f"Expected every followed event line to be a JSON object, got: {follow_result.stdout!r}"
    )


@pytest.mark.release
@pytest.mark.timeout(120)
def test_troubleshoot_follow_events_unknown_agent(e2e: E2eSession) -> None:
    # Unhappy path for the same tutorial block: following a nonexistent agent
    # must fail fast at target resolution (before entering the stream loop)
    # with a clear error, rather than hanging or silently producing no output.
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # follow events in real time while reproducing an issue
        mngr event my-task --follow
    """)
    # `timeout` is only a safety net: a correct resolution failure exits long
    # before it fires. If the command instead hung, `timeout` would kill it and
    # the exit-code-124 assertion below would catch the regression.
    result = e2e.run("timeout 30 mngr event no-such-agent --follow", comment="follow events for a nonexistent agent")
    expect(result).to_fail()
    assert result.exit_code != 124, f"command hung until `timeout` killed it: {result.stderr!r}"
    # The failure must be a clean target-resolution error that names the agent --
    # the same diagnostic the non-follow sibling asserts -- proving --follow fails
    # at resolution before entering the stream loop, not via some other error.
    expect(result.stderr).to_contain("Could not find agent")
    expect(result.stderr).to_contain("no-such-agent")


@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.timeout(60)
def test_troubleshoot_transcript_for_errors(e2e: E2eSession) -> None:
    # In the tutorial, my-task is a transcript-producing (claude) agent. Here we
    # substitute the lightweight `command` agent used throughout these tutorial
    # tests, which deliberately does not produce a common transcript. So the
    # exact tutorial command runs but is expected to fail fast with a clear,
    # actionable diagnostic -- itself a useful troubleshooting behavior to lock in.
    #
    # Unlike the sibling diagnostics, this test is intentionally not marked
    # @pytest.mark.modal or @pytest.mark.rsync: the diagnostic is a client-side
    # agent-type check, and `mngr transcript` resolves the agent via the local
    # discovery hint, so it never scans the modal provider. The agent is local
    # and created with --no-connect, so no file sync (rsync) ever runs either.
    # The other thin tests use full-discovery commands (mngr list/event) that do
    # reach modal, and exec/start-based tests that drive rsync. The local command
    # agent's tmux session is set up at create time, so @pytest.mark.tmux stays.
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # check the agent's transcript for error messages
        mngr transcript my-task --tail 10
    """)
    _create_my_task(e2e, 101023)
    result = e2e.run("mngr transcript my-task --tail 10", comment="check transcript for error messages")
    expect(result).to_fail()
    expect(result.stderr).to_contain("my-task")
    expect(result.stderr).to_contain("does not produce a common transcript")


@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.timeout(120)
def test_troubleshoot_host_diagnostics(e2e: E2eSession) -> None:
    # No @pytest.mark.rsync: this exercises a *local* command agent, whose work
    # dir is created via git-worktree and whose `mngr exec` runs on localhost.
    # rsync is only invoked for cross-locality file transfer (exactly one remote
    # endpoint), so declaring the rsync mark here trips the guard's
    # "marked rsync but never invoked rsync" NEVER_INVOKED check.
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # run commands on the host to diagnose issues
        mngr exec my-task "cat /var/log/syslog | tail -20"
        mngr exec my-task "ps aux"
        mngr exec my-task "df -h"
    """)
    _create_my_task(e2e, 101024)
    # The exec COMMAND is a single quoted argument run by the host's shell, so
    # the pipe in the cat command executes on the host. /var/log/syslog may not
    # exist (e.g. on macOS hosts); allow that command to fail but still require
    # mngr to forward it.
    e2e.run('mngr exec my-task "cat /var/log/syslog | tail -20" || true', comment="cat syslog")
    # ps aux must run on the agent's host -- verify it reports the agent's own
    # `sleep 101024` process, proving exec reached the right host.
    ps_result = e2e.run('mngr exec my-task "ps aux"', comment="ps aux")
    expect(ps_result).to_succeed()
    assert "sleep 101024" in ps_result.stdout, f"ps aux did not show the agent's sleep process:\n{ps_result.stdout}"
    # df -h must report at least one mounted filesystem.
    df_result = e2e.run('mngr exec my-task "df -h"', comment="df -h")
    expect(df_result).to_succeed()
    assert "Filesystem" in df_result.stdout, f"df -h did not report a filesystem table:\n{df_result.stdout}"


@pytest.mark.release
@pytest.mark.timeout(120)
def test_troubleshoot_host_diagnostics_missing_agent(e2e: E2eSession) -> None:
    # Unhappy path for the same tutorial block: pointing a host-diagnostic exec
    # at an agent that does not exist (a typo, or one that was already destroyed)
    # must fail fast at target resolution with a clear "could not find" error,
    # rather than silently running the diagnostic on the wrong host or hanging.
    # Resolving an unknown name forces a full provider scan, but no agent is
    # found and no host is provisioned, so this exercises no tmux/rsync/modal
    # resources (mirroring the missing-agent sibling tests above).
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # run commands on the host to diagnose issues
        mngr exec my-task "cat /var/log/syslog | tail -20"
        mngr exec my-task "ps aux"
        mngr exec my-task "df -h"
    """)
    result = e2e.run('mngr exec no-such-agent-zzz "ps aux"', comment="exec on a missing agent")
    expect(result).to_fail()
    expect(result.stderr).to_contain("no-such-agent-zzz")


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.timeout(120)
def test_troubleshoot_stop_restart(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # if an agent is stuck, try stopping and restarting it
        mngr stop my-task
        mngr start my-task --connect
    """)
    _create_my_task(e2e, 101025)

    # The command agent's whole job is to run `sleep 101025`, so the presence
    # of that process is a direct, provider-agnostic proxy for whether the
    # agent is actually running. The bracketed "[s]" keeps pgrep from matching
    # its own command line. pgrep exits 0 when a match is found, 1 otherwise.
    sleep_running = 'pgrep -f "[s]leep 101025"'

    # Freshly created, the agent (and thus its sleep process) should be running.
    expect(e2e.run(sleep_running, comment="confirm the agent's process is running before stop")).to_succeed()

    # Stopping a stuck agent should tear down its process.
    expect(e2e.run("mngr stop my-task", comment="stop the agent")).to_succeed()
    expect(e2e.run(sleep_running, comment="confirm the agent's process is gone after stop")).to_fail()

    # Restarting should bring the process back up.
    expect(e2e.run("mngr start my-task --connect", comment="start and reconnect")).to_succeed()
    expect(e2e.run(sleep_running, comment="confirm the agent's process is running again after restart")).to_succeed()


@pytest.mark.release
@pytest.mark.modal
@pytest.mark.rsync
# This test runs two full Modal creates plus a destroy whose post-destroy GC
# pass scans every provider over the network. Each of those steps is minutes-
# scale, so the test-level timeout must comfortably exceed their sum (the
# default 240s was too tight once the destroy was given room to finish GC).
@pytest.mark.timeout(420)
def test_troubleshoot_destroy_and_recreate_modal(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # if a host is in a bad state, destroy and recreate
        mngr destroy my-task --force
        mngr create my-task --provider modal
    """)
    # The tutorial block uses a bare "mngr create my-task --provider modal",
    # which assumes the reader has a default agent type configured. The
    # isolated e2e environment has no default, so we pin --type command (with a
    # sleep stand-in) to avoid the modal claude startup cost, matching the
    # pattern used by the other modal tutorial tests.
    expect(
        e2e.run(
            "mngr create my-task --provider modal --type command --no-connect --no-ensure-clean -- sleep 101026",
            comment="create modal my-task to destroy",
            timeout=180.0,
        )
    ).to_succeed()

    # The agent should exist on a modal host before we destroy it. Capture the
    # host name so we can confirm the recreate lands on a genuinely fresh host.
    # Scope the verification listings to --provider modal: my-task only ever
    # lives on modal here, and an unscoped full-discovery `mngr list` would also
    # query every other registered backend (aws, azure, ...). Those backends
    # raise ProviderUnavailableError when their credentials are absent (by
    # design -- a misconfigured provider stays visible), which makes `mngr list`
    # exit non-zero in environments without those creds. Scoping keeps this
    # modal-focused test independent of unrelated cloud credentials and faster,
    # matching the --provider scoping pattern used by the agent-type tests.
    before = e2e.run("mngr list --provider modal --format json", comment="confirm my-task exists before destroy")
    expect(before).to_succeed()
    agents_before = [a for a in json.loads(before.stdout)["agents"] if a["name"] == "my-task"]
    assert len(agents_before) == 1, f"expected exactly one my-task before destroy, got {agents_before}"
    original_host = agents_before[0]["host"]["name"]

    # Destroy runs the default post-destroy GC pass (see cli/destroy.py), which
    # scans every provider -- including Modal -- over the network and routinely
    # takes longer than the default 30s e2e.run timeout. Give it a generous
    # timeout so the command can finish GC rather than being killed (exit 124)
    # after the agent itself is already torn down.
    expect(e2e.run("mngr destroy my-task --force", comment="destroy", timeout=120.0)).to_succeed()

    # After destroy the agent (and its now-empty host) must be gone.
    after_destroy = e2e.run(
        "mngr list --provider modal --format json", comment="confirm my-task is gone after destroy"
    )
    expect(after_destroy).to_succeed()
    names_after_destroy = [a["name"] for a in json.loads(after_destroy.stdout)["agents"]]
    assert "my-task" not in names_after_destroy, f"my-task should be gone after destroy, saw {names_after_destroy}"

    expect(
        e2e.run(
            "mngr create my-task --provider modal --type command --no-connect --no-ensure-clean -- sleep 101026",
            comment="recreate",
            timeout=180.0,
        )
    ).to_succeed()

    # The recreate must bring my-task back, and on a brand-new host (the old one
    # was destroyed), not by silently resurrecting the destroyed host.
    after = e2e.run("mngr list --provider modal --format json", comment="confirm my-task is back after recreate")
    expect(after).to_succeed()
    agents_after = [a for a in json.loads(after.stdout)["agents"] if a["name"] == "my-task"]
    assert len(agents_after) == 1, f"expected exactly one my-task after recreate, got {agents_after}"
    recreated_host = agents_after[0]["host"]["name"]
    assert recreated_host != original_host, f"recreate should land on a fresh host, but reused {original_host!r}"


# No @pytest.mark.modal: in a fresh environment there are no agents and the
# Modal environment does not exist yet, so `mngr gc` skips the modal provider
# (ProviderEmptyError) instead of creating an environment. gc's host discovery
# talks to Modal only over the in-process gRPC SDK, which the resource guard
# cannot observe across the e2e subprocess boundary -- the only Modal usage it
# can observe is an actual `modal` CLI invocation, which gc never makes here.
# Marking the test @pytest.mark.modal would therefore trip the guard's "marked
# but never invoked" check.
@pytest.mark.release
@pytest.mark.timeout(120)
def test_troubleshoot_gc_dry_run_then_gc(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # garbage collect to clean up any orphaned resources
        mngr gc --dry-run
        mngr gc
    """)
    # gc walks every configured provider, which can take well over the default
    # 10s pytest timeout, so the test carries an explicit timeout and each
    # command gets a generous per-run timeout.
    dry_run_result = e2e.run("mngr gc --dry-run", comment="dry-run gc", timeout=60.0)
    expect(dry_run_result).to_succeed()
    # The dry-run must announce itself as a dry run so the user knows nothing was
    # actually destroyed -- this is the distinction the tutorial block teaches.
    expect(dry_run_result.stdout).to_contain("Dry Run")
    # A fresh environment has nothing orphaned, so the dry run should report it
    # found nothing rather than claiming it would destroy something.
    expect(dry_run_result.stdout).to_contain("No resources found to destroy")

    real_result = e2e.run("mngr gc", comment="run gc", timeout=60.0)
    expect(real_result).to_succeed()
    # The real run reports actual results, not a dry run: its header must differ
    # from the dry-run header so a reader can tell the two invocations apart.
    expect(real_result.stdout).to_contain("Garbage Collection Results")
    assert "Dry Run" not in real_result.stdout, (
        f"real gc run should not be labeled a dry run, got: {real_result.stdout}"
    )
    expect(real_result.stdout).to_contain("No resources found to destroy")
