"""Tests for the TROUBLESHOOTING tutorial section.

The blocks in this section are short diagnostic commands prefixed with
"auto-generated by Claude, remove when a human has sanctioned this" -- the
matcher treats them as real blocks, so each gets a thin test that just
verifies the command runs cleanly against a real my-task agent.
"""

import pytest

from imbue.mngr.e2e.conftest import E2eSession
from imbue.skitwright.expect import expect


def _create_my_task(e2e: E2eSession, sleep_value: int) -> None:
    expect(
        e2e.run(
            f"mngr create my-task --type command --no-ensure-clean --no-connect -- sleep {sleep_value}",
            comment=f"create my-task (sleep {sleep_value})",
        )
    ).to_succeed()


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.modal
def test_troubleshoot_check_agent_state(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # check if the agent exists and its current state
        mngr list --fields "name,state,host.provider,host.name"
    """)
    _create_my_task(e2e, 101020)
    expect(
        e2e.run(
            'mngr list --fields "name,state,host.provider,host.name"',
            comment="check if the agent exists and its current state",
        )
    ).to_succeed()


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.modal
def test_troubleshoot_recent_events(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # view recent events to understand what happened
        mngr event my-task --tail 20
    """)
    _create_my_task(e2e, 101021)
    expect(e2e.run("mngr event my-task --tail 20", comment="view recent events")).to_succeed()


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.modal
def test_troubleshoot_follow_events(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # follow events in real time while reproducing an issue
        mngr event my-task --follow
    """)
    _create_my_task(e2e, 101022)
    expect(
        e2e.run("timeout 1 mngr event my-task --follow || true", comment="follow events while reproducing")
    ).to_succeed()


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.modal
def test_troubleshoot_transcript_for_errors(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # check the agent's transcript for error messages
        mngr transcript my-task --tail 10
    """)
    _create_my_task(e2e, 101023)
    expect(e2e.run("mngr transcript my-task --tail 10", comment="check transcript for error messages")).to_succeed()


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.modal
def test_troubleshoot_host_diagnostics(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # run commands on the host to diagnose issues
        mngr exec my-task -- cat /var/log/syslog | tail -20
        mngr exec my-task -- ps aux
        mngr exec my-task -- df -h
    """)
    _create_my_task(e2e, 101024)
    # /var/log/syslog may not exist (e.g. on macOS hosts); allow failure for
    # the cat and require only that mngr forwards the commands.
    e2e.run("mngr exec my-task -- cat /var/log/syslog | tail -20 || true", comment="cat syslog")
    expect(e2e.run("mngr exec my-task -- ps aux", comment="ps aux")).to_succeed()
    expect(e2e.run("mngr exec my-task -- df -h", comment="df -h")).to_succeed()


@pytest.mark.rsync
@pytest.mark.release
@pytest.mark.tmux
@pytest.mark.modal
def test_troubleshoot_stop_restart(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # if an agent is stuck, try stopping and restarting it
        mngr stop my-task
        mngr start my-task --connect
    """)
    _create_my_task(e2e, 101025)
    expect(e2e.run("mngr stop my-task", comment="stop the agent")).to_succeed()
    expect(e2e.run("mngr start my-task --connect", comment="start and reconnect")).to_succeed()


@pytest.mark.release
@pytest.mark.modal
@pytest.mark.rsync
@pytest.mark.timeout(240)
def test_troubleshoot_destroy_and_recreate_modal(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # if a host is in a bad state, destroy and recreate
        mngr destroy my-task --force
        mngr create my-task --provider modal
    """)
    expect(
        e2e.run(
            "mngr create my-task --provider modal --no-connect --no-ensure-clean",
            comment="create modal my-task to destroy",
            timeout=180.0,
        )
    ).to_succeed()
    expect(e2e.run("mngr destroy my-task --force", comment="destroy")).to_succeed()
    expect(
        e2e.run(
            "mngr create my-task --provider modal --no-connect --no-ensure-clean",
            comment="recreate",
            timeout=180.0,
        )
    ).to_succeed()


@pytest.mark.release
@pytest.mark.modal
def test_troubleshoot_gc_dry_run_then_gc(e2e: E2eSession) -> None:
    e2e.write_tutorial_block("""
        # auto-generated by Claude, remove when a human has sanctioned this
        # garbage collect to clean up any orphaned resources
        mngr gc --dry-run
        mngr gc
    """)
    expect(e2e.run("mngr gc --dry-run", comment="dry-run gc")).to_succeed()
    expect(e2e.run("mngr gc", comment="run gc")).to_succeed()
