"""Synchronous HTTP client for the latchkey gateway's bundled extensions.

The shared latchkey gateway (spawned by ``mngr latchkey forward``)
exposes two extensions added in version 2.9.0:

* ``permission-requests`` -- pending-permission queue. Agents POST to
  ``/permission-requests`` when they hit a blocked service; the desktop
  client consumes ``GET /permission-requests?follow=true`` to learn
  about new requests and ``DELETE /permission-requests/<id>`` to remove
  them once granted or denied.
* ``permissions`` -- per-host permissions config editor. The desktop
  client POSTs to ``/permissions/rules?path=<host_file>&rule_key=<scope>``
  with a JSON body of permission-schema names to apply a grant.

Both extensions sit behind the gateway's standard auth wall: callers
present the listen password in ``Authorization: Bearer <password>`` and
a permissions-override JWT in
``X-Latchkey-Gateway-Permissions-Override``. This client always sends
the admin JWT (minted via :meth:`Latchkey.create_admin_permissions_jwt`)
because the desktop client needs wildcard access to both extensions.

All operations are synchronous. The streaming consumer in
:mod:`permission_requests_consumer` drives the long-running
``?follow=true`` connection from a daemon thread; everything else is
called from the FastAPI request thread under
``asyncio.get_running_loop().run_in_executor``.
"""

import json
import threading
from collections.abc import Iterator
from collections.abc import Sequence
from pathlib import Path
from typing import Final

import httpx
from loguru import logger
from pydantic import Field
from pydantic import PrivateAttr

from imbue.imbue_common.frozen_model import FrozenModel
from imbue.imbue_common.mutable_model import MutableModel
from imbue.mngr_latchkey.core import Latchkey
from imbue.mngr_latchkey.forward_supervisor import is_forward_info_alive
from imbue.mngr_latchkey.store import LatchkeyForwardInfo
from imbue.mngr_latchkey.store import load_forward_info

# Header names baked into the upstream gateway's wire contract.
_HEADER_PASSWORD: Final[str] = "X-Latchkey-Gateway-Password"
_HEADER_PERMISSIONS_OVERRIDE: Final[str] = "X-Latchkey-Gateway-Permissions-Override"

# Per-line read timeout on the follow stream. Finite (not ``None``) so
# the consumer thread can exit promptly on shutdown -- a read=None would
# leave the consumer wedged inside ``response.iter_lines()`` until the
# gateway happened to push the next request, which on a clean shutdown
# is never, and the root concurrency group would then time out waiting
# for the thread to join. The trade-off is that an idle stream gets torn
# down and rebuilt every ~2 seconds, which is fine for the local
# 127.0.0.1 gateway (negligible network cost) and bounds shutdown delay
# to one read-timeout interval. The consumer's reconnect loop treats a
# ReadTimeout-driven close as "no work to do", not as an error.
_FOLLOW_READ_TIMEOUT: Final[httpx.Timeout] = httpx.Timeout(connect=10.0, read=2.0, write=10.0, pool=10.0)

# Short timeout for one-shot POST / DELETE / GET calls.
_ONE_SHOT_TIMEOUT_SECONDS: Final[float] = 10.0

# How long minds is willing to wait for ``mngr latchkey forward`` to
# bind its gateway port and stamp the port onto its on-disk supervisor
# record. Long enough to tolerate a cold gateway-binary start on a
# slow box but short enough to keep ``minds run`` from blocking
# forever if the supervisor never becomes ready.
_GATEWAY_PORT_WAIT_SECONDS: Final[float] = 30.0
_GATEWAY_PORT_POLL_INTERVAL_SECONDS: Final[float] = 0.2


class LatchkeyGatewayClientError(Exception):
    """Raised for any HTTP / parse failure when talking to the gateway."""


class LatchkeyGatewayInitializationError(LatchkeyGatewayClientError):
    """Raised when initialization didn't succeed."""


class LatchkeyGatewayClientNotInitializedError(LatchkeyGatewayClientError):
    """Raised when the client isn't initialized yet."""


class StreamedPermissionRequest(FrozenModel):
    """Single JSONL record produced by ``GET /permission-requests``."""

    request_id: str = Field(description="Filename-safe request id generated by the extension.")
    agent_id: str = Field(description="Agent that submitted the request.")
    service_name: str = Field(description="Latchkey service the agent wants to reach.")
    rationale: str = Field(description="One-paragraph human-readable rationale supplied by the agent.")


class LatchkeyGatewayClient(MutableModel):
    """Synchronous client for the latchkey gateway's HTTP extensions.

    The client owns a single :class:`httpx.Client` used for everything
    except the long-lived follow-stream (which gets its own short-lived
    client per connect attempt so a stream restart cannot poison the
    pool used by the request thread).
    """

    _latchkey: Latchkey | None = PrivateAttr(default=None)

    _transport: httpx.BaseTransport | None = PrivateAttr(default=None)
    _base_url: str | None = PrivateAttr(default=None)
    _password: str | None = PrivateAttr(default=None)
    _admin_jwt: str | None = PrivateAttr(default=None)

    _init_lock: threading.Lock = PrivateAttr(default_factory=threading.Lock)

    # ``httpx.BaseTransport`` is not pydantic-native; allow it through.
    model_config = {"arbitrary_types_allowed": True, "frozen": False, "extra": "forbid"}

    def ensure_initialized(self) -> None:
        """Block until the supervised ``mngr latchkey forward`` binds its gateway port, then derive credentials.

        Idempotent: subsequent calls return immediately once the
        credentials have been populated. Ideally avoid running this on
        the main thread; ``minds run`` kicks it off from a background
        thread so startup does not block on the supervisor.

        Requires ``self.latchkey`` to be set; tests that pre-populate
        the private credential attrs directly skip this entirely.
        """
        with self._init_lock:
            if self._base_url is not None:
                # Already initialized.
                return
            if self._latchkey is None:
                raise LatchkeyGatewayClientNotInitializedError(
                    "LatchkeyGatewayClient was constructed without a Latchkey instance; cannot initialize.",
                )
            forward_info = self._wait_for_gateway_port()
            self._base_url = f"http://{self._latchkey.listen_host}:{forward_info.gateway_port}"
            self._admin_jwt = self._latchkey.create_admin_permissions_jwt()
            self._password = self._latchkey.derive_gateway_password()

    @classmethod
    def from_latchkey(cls, latchkey: Latchkey) -> "LatchkeyGatewayClient":
        client = cls()
        client._latchkey = latchkey
        return client

    @classmethod
    def from_credentials(
        cls, base_url: str, password: str, admin_jwt: str, transport: httpx.BaseTransport | None = None
    ) -> "LatchkeyGatewayClient":
        client = cls()
        client._base_url = base_url
        client._password = password
        client._admin_jwt = admin_jwt
        client._transport = transport
        return client

    def _require_base_url(self) -> str:
        if self._base_url is None:
            raise LatchkeyGatewayClientNotInitializedError("LatchkeyGatewayClient is not initialized yet.")
        return self._base_url

    def _wait_for_gateway_port(self) -> LatchkeyForwardInfo:
        """Block until the supervised ``mngr latchkey forward`` stamps its bound gateway port.

        The supervisor writes its ``LatchkeyForwardInfo`` record with
        ``gateway_port=None`` at spawn time and updates the record in place
        once it has bound the shared ``latchkey gateway`` subprocess to a
        free TCP port. We poll the record until the port becomes non-None
        (or the timeout expires) so subsequent minds startup steps can
        build the gateway URL deterministically without racing the
        supervisor's own startup.
        """
        if self._latchkey is None:
            raise LatchkeyGatewayInitializationError(
                "LatchkeyGatewayClient was constructed without a Latchkey instance; cannot wait for gateway port.",
            )
        plugin_dir = self._latchkey.plugin_data_dir
        deadline = threading.Event()
        timer = threading.Timer(_GATEWAY_PORT_WAIT_SECONDS, deadline.set)
        timer.daemon = True
        timer.start()
        try:
            while not deadline.is_set():
                info = load_forward_info(plugin_dir)
                if info is not None and not is_forward_info_alive(info):
                    # Supervisor died between spawn and port-bind; bail out
                    # instead of polling a stale record forever.
                    raise LatchkeyGatewayInitializationError(
                        "The ``mngr latchkey forward`` supervisor we spawned has died before binding its "
                        f"gateway port; check {plugin_dir}/latchkey_forward.log for details.",
                    )
                if info is not None and info.gateway_port is not None:
                    return info
                # Use the same event as the deadline so we wake up promptly
                # when the timer fires; the wait returns True iff the
                # deadline was reached during the sleep.
                if deadline.wait(timeout=_GATEWAY_PORT_POLL_INTERVAL_SECONDS):
                    break
        finally:
            timer.cancel()
        raise LatchkeyGatewayInitializationError(
            f"Timed out after {_GATEWAY_PORT_WAIT_SECONDS:.1f}s waiting for ``mngr latchkey forward`` to stamp "
            f"its bound gateway port onto {plugin_dir}; is the supervisor stuck?",
        )

    def _build_headers(self) -> dict[str, str]:
        if self._password is None or self._admin_jwt is None:
            raise LatchkeyGatewayClientNotInitializedError("LatchkeyGatewayClient is not initialized yet.")
        return {
            _HEADER_PASSWORD: self._password,
            _HEADER_PERMISSIONS_OVERRIDE: self._admin_jwt,
        }

    def _one_shot_client(self) -> httpx.Client:
        """Return a per-call :class:`httpx.Client` honouring the optional test transport."""
        if self._transport is not None:
            return httpx.Client(timeout=_ONE_SHOT_TIMEOUT_SECONDS, transport=self._transport)
        return httpx.Client(timeout=_ONE_SHOT_TIMEOUT_SECONDS)

    def _stream_client(self) -> httpx.Client:
        """Return a per-stream :class:`httpx.Client` honouring the optional test transport."""
        if self._transport is not None:
            return httpx.Client(timeout=_FOLLOW_READ_TIMEOUT, transport=self._transport)
        return httpx.Client(timeout=_FOLLOW_READ_TIMEOUT)

    def iter_permission_requests(self) -> Iterator[StreamedPermissionRequest]:
        """Yield every existing + future pending permission request until the connection drops.

        Connects to ``GET /permission-requests?follow=true`` and parses
        each newline-delimited JSON line as a
        :class:`StreamedPermissionRequest`. The iterator is exhausted
        (raising :class:`LatchkeyGatewayClientError` on any HTTP error)
        when the gateway closes the connection or a network error
        terminates the stream.

        ``httpx.ReadTimeout`` is treated specially: the stream uses a
        finite per-read timeout (see ``_FOLLOW_READ_TIMEOUT``) so the
        consumer thread can unblock on shutdown, and a timeout therefore
        means "no events arrived in the polling window" -- not an
        error. We swallow it and return cleanly so the caller's
        reconnect loop can decide whether to keep going (idle) or exit
        (stop event set).
        """
        self.ensure_initialized()
        url = f"{self._require_base_url().rstrip('/')}/permission-requests"
        params = {"follow": "true"}
        try:
            with self._stream_client() as client:
                with client.stream("GET", url, params=params, headers=self._build_headers()) as response:
                    response.raise_for_status()
                    for raw_line in response.iter_lines():
                        line = raw_line.strip()
                        if not line:
                            continue
                        try:
                            data = json.loads(line)
                        except json.JSONDecodeError as e:
                            logger.warning("Could not parse permission-requests JSONL line {!r}: {}", line, e)
                            continue
                        try:
                            yield StreamedPermissionRequest.model_validate(data)
                        except ValueError as e:
                            logger.warning(
                                "permission-requests JSONL line had unexpected shape {!r}: {}",
                                line,
                                e,
                            )
                            continue
        except httpx.ReadTimeout:
            # Idle window -- not an error. Return so the caller's
            # reconnect loop can check its stop event and either exit or
            # reconnect promptly without backoff.
            return
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"GET /permission-requests stream failed: {e}") from e

    def delete_permission_request(self, request_id: str) -> None:
        """Remove the named pending request from the gateway's queue.

        404s are tolerated because the desktop-client UI may race the
        gateway (e.g. when the same request is granted and deny is
        clicked in a different tab); the intent is satisfied either
        way.
        """
        self.ensure_initialized()
        url = f"{self._require_base_url().rstrip('/')}/permission-requests/{request_id}"
        try:
            with self._one_shot_client() as client:
                response = client.delete(url, headers=self._build_headers())
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"DELETE {url} failed: {e}") from e
        if response.status_code == 404:
            logger.debug("DELETE {} returned 404; request already gone", url)
            return
        if response.status_code >= 400:
            raise LatchkeyGatewayClientError(
                f"DELETE {url} returned {response.status_code}: {response.text.strip()}",
            )

    def get_granted_permissions_for_scopes(
        self,
        permissions_file_path: Path,
        scopes: Sequence[str],
    ) -> frozenset[str]:
        """Return the union of granted permission schemas across ``scopes`` in the file.

        Wraps ``GET /permissions?path=<...>`` and walks the parsed
        ``rules`` list. A missing file (404) is treated as "no rules"
        and returns the empty set, matching the previous filesystem
        read's behaviour. Any other non-2xx surfaces as
        :class:`LatchkeyGatewayClientError`.
        """
        self.ensure_initialized()
        url = f"{self._require_base_url().rstrip('/')}/permissions"
        params = {"path": str(permissions_file_path)}
        try:
            with self._one_shot_client() as client:
                response = client.get(url, params=params, headers=self._build_headers())
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"GET {url} failed: {e}") from e
        if response.status_code == 404:
            return frozenset()
        if response.status_code >= 400:
            raise LatchkeyGatewayClientError(
                f"GET {url} returned {response.status_code}: {response.text.strip()}",
            )
        try:
            payload = response.json()
        except ValueError as e:
            raise LatchkeyGatewayClientError(f"GET {url} returned non-JSON body: {e}") from e
        if not isinstance(payload, dict):
            raise LatchkeyGatewayClientError(f"GET {url} returned non-object JSON: {payload!r}")
        rules = payload.get("rules")
        if not isinstance(rules, list):
            return frozenset()
        scopes_set = set(scopes)
        granted: set[str] = set()
        for rule in rules:
            if not isinstance(rule, dict):
                continue
            for scope_name, permissions in rule.items():
                if scope_name in scopes_set and isinstance(permissions, list):
                    granted.update(p for p in permissions if isinstance(p, str))
        return frozenset(granted)

    def set_permission_rule(
        self,
        permissions_file_path: Path,
        rule_key: str,
        granted_permissions: Sequence[str],
    ) -> None:
        """Add or replace the rule for ``rule_key`` in ``permissions_file_path``.

        Wraps ``POST /permissions/rules?path=<...>&rule_key=<...>`` with
        a JSON-array body of permission-schema names. The extension
        creates the target file if it does not yet exist; it refuses
        any path outside ``LATCHKEY_EXTENSION_PERMISSIONS_ROOT`` with
        a 403, which we surface verbatim so misconfigurations are
        loud.
        """
        self.ensure_initialized()
        url = f"{self._require_base_url().rstrip('/')}/permissions/rules"
        params = {"path": str(permissions_file_path), "rule_key": rule_key}
        try:
            with self._one_shot_client() as client:
                response = client.post(
                    url,
                    params=params,
                    json=list(granted_permissions),
                    headers=self._build_headers(),
                )
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"POST {url} failed: {e}") from e
        if response.status_code >= 400:
            raise LatchkeyGatewayClientError(
                f"POST {url} returned {response.status_code}: {response.text.strip()}",
            )
