"""Synchronous HTTP client for the latchkey gateway's bundled extensions.

The shared latchkey gateway (spawned by ``mngr latchkey forward``)
exposes two extensions added in version 2.9.0:

* ``permission-requests`` -- pending-permission queue. Agents POST to
  ``/permission-requests`` when they hit a blocked service; the desktop
  client consumes ``GET /permission-requests?follow=true`` to learn
  about new requests and ``DELETE /permission-requests/<id>`` to remove
  them once granted or denied.
* ``permissions`` -- per-host permissions config editor. The desktop
  client POSTs to ``/permissions/rules?path=<host_file>&rule_key=<scope>``
  with a JSON body of permission-schema names to apply a grant.

Both extensions sit behind the gateway's standard auth wall: callers
present the listen password in ``Authorization: Bearer <password>`` and
a permissions-override JWT in
``X-Latchkey-Gateway-Permissions-Override``. This client always sends
the admin JWT (minted via :meth:`Latchkey.create_admin_permissions_jwt`)
because the desktop client needs wildcard access to both extensions.

All operations are synchronous. The streaming consumer in
:mod:`permission_requests_consumer` drives the long-running
``?follow=true`` connection from a daemon thread; everything else is
called from the FastAPI request thread under
``asyncio.get_running_loop().run_in_executor``.
"""

import json
from collections.abc import Iterator
from collections.abc import Sequence
from pathlib import Path
from typing import Final

import httpx
from loguru import logger
from pydantic import Field

from imbue.imbue_common.frozen_model import FrozenModel
from imbue.imbue_common.mutable_model import MutableModel

# Header names baked into the upstream gateway's wire contract.
_HEADER_PASSWORD: Final[str] = "X-Latchkey-Gateway-Password"
_HEADER_PERMISSIONS_OVERRIDE: Final[str] = "X-Latchkey-Gateway-Permissions-Override"

# The follow-stream connection is held open for the lifetime of the
# desktop-client process; the per-line read timeout has to be ``None``
# so it does not fire during the (intentional) long quiet periods
# between requests.
_FOLLOW_READ_TIMEOUT: Final[httpx.Timeout] = httpx.Timeout(connect=10.0, read=None, write=10.0, pool=10.0)

# Short timeout for one-shot POST / DELETE / GET calls.
_ONE_SHOT_TIMEOUT_SECONDS: Final[float] = 10.0


class LatchkeyGatewayClientError(Exception):
    """Raised for any HTTP / parse failure when talking to the gateway."""


class StreamedPermissionRequest(FrozenModel):
    """Single JSONL record produced by ``GET /permission-requests``."""

    request_id: str = Field(description="Filename-safe request id generated by the extension.")
    agent_id: str = Field(description="Agent that submitted the request.")
    service_name: str = Field(description="Latchkey service the agent wants to reach.")
    rationale: str = Field(description="One-paragraph human-readable rationale supplied by the agent.")


class LatchkeyGatewayClient(MutableModel):
    """Synchronous client for the latchkey gateway's HTTP extensions.

    The client owns a single :class:`httpx.Client` used for everything
    except the long-lived follow-stream (which gets its own short-lived
    client per connect attempt so a stream restart cannot poison the
    pool used by the request thread).
    """

    base_url: str = Field(
        frozen=True,
        description="Base URL of the shared gateway, e.g. ``http://127.0.0.1:32867``.",
    )
    password: str = Field(
        frozen=True,
        description="Listen password the gateway accepts in ``Authorization: Bearer <password>``.",
    )
    admin_jwt: str = Field(
        frozen=True,
        description=(
            "Wildcard ``permissions-override`` JWT the desktop client uses to reach the "
            "gateway's extension endpoints. Minted at startup via "
            ":meth:`Latchkey.create_admin_permissions_jwt`."
        ),
    )
    transport: httpx.BaseTransport | None = Field(
        default=None,
        description=(
            "Optional custom :class:`httpx.BaseTransport` to use for every request. "
            "Tests inject an :class:`httpx.MockTransport` here so the client can be exercised "
            "without a real network endpoint; production callers leave it ``None`` to get "
            "the httpx default transport."
        ),
    )

    # ``httpx.BaseTransport`` is not pydantic-native; allow it through.
    model_config = {"arbitrary_types_allowed": True, "frozen": False, "extra": "forbid"}

    def _build_headers(self) -> dict[str, str]:
        return {
            _HEADER_PASSWORD: self.password,
            _HEADER_PERMISSIONS_OVERRIDE: self.admin_jwt,
        }

    def _one_shot_client(self) -> httpx.Client:
        """Return a per-call :class:`httpx.Client` honouring the optional test transport."""
        if self.transport is not None:
            return httpx.Client(timeout=_ONE_SHOT_TIMEOUT_SECONDS, transport=self.transport)
        return httpx.Client(timeout=_ONE_SHOT_TIMEOUT_SECONDS)

    def _stream_client(self) -> httpx.Client:
        """Return a per-stream :class:`httpx.Client` honouring the optional test transport."""
        if self.transport is not None:
            return httpx.Client(timeout=_FOLLOW_READ_TIMEOUT, transport=self.transport)
        return httpx.Client(timeout=_FOLLOW_READ_TIMEOUT)

    def iter_permission_requests(self) -> Iterator[StreamedPermissionRequest]:
        """Yield every existing + future pending permission request until the connection drops.

        Connects to ``GET /permission-requests?follow=true`` and parses
        each newline-delimited JSON line as a
        :class:`StreamedPermissionRequest`. The iterator is exhausted
        (raising :class:`LatchkeyGatewayClientError` on any HTTP error)
        when the gateway closes the connection or a network error
        terminates the stream.
        """
        url = f"{self.base_url.rstrip('/')}/permission-requests"
        params = {"follow": "true"}
        try:
            with self._stream_client() as client:
                with client.stream("GET", url, params=params, headers=self._build_headers()) as response:
                    response.raise_for_status()
                    for raw_line in response.iter_lines():
                        line = raw_line.strip()
                        if not line:
                            continue
                        try:
                            data = json.loads(line)
                        except json.JSONDecodeError as e:
                            logger.warning("Could not parse permission-requests JSONL line {!r}: {}", line, e)
                            continue
                        try:
                            yield StreamedPermissionRequest.model_validate(data)
                        except ValueError as e:
                            logger.warning(
                                "permission-requests JSONL line had unexpected shape {!r}: {}",
                                line,
                                e,
                            )
                            continue
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"GET /permission-requests stream failed: {e}") from e

    def delete_permission_request(self, request_id: str) -> None:
        """Remove the named pending request from the gateway's queue.

        404s are tolerated because the desktop-client UI may race the
        gateway (e.g. when the same request is granted and deny is
        clicked in a different tab); the intent is satisfied either
        way.
        """
        url = f"{self.base_url.rstrip('/')}/permission-requests/{request_id}"
        try:
            with self._one_shot_client() as client:
                response = client.delete(url, headers=self._build_headers())
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"DELETE {url} failed: {e}") from e
        if response.status_code == 404:
            logger.debug("DELETE {} returned 404; request already gone", url)
            return
        if response.status_code >= 400:
            raise LatchkeyGatewayClientError(
                f"DELETE {url} returned {response.status_code}: {response.text.strip()}",
            )

    def get_granted_permissions_for_scopes(
        self,
        permissions_file_path: Path,
        scopes: Sequence[str],
    ) -> frozenset[str]:
        """Return the union of granted permission schemas across ``scopes`` in the file.

        Wraps ``GET /permissions?path=<...>`` and walks the parsed
        ``rules`` list. A missing file (404) is treated as "no rules"
        and returns the empty set, matching the previous filesystem
        read's behaviour. Any other non-2xx surfaces as
        :class:`LatchkeyGatewayClientError`.
        """
        url = f"{self.base_url.rstrip('/')}/permissions"
        params = {"path": str(permissions_file_path)}
        try:
            with self._one_shot_client() as client:
                response = client.get(url, params=params, headers=self._build_headers())
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"GET {url} failed: {e}") from e
        if response.status_code == 404:
            return frozenset()
        if response.status_code >= 400:
            raise LatchkeyGatewayClientError(
                f"GET {url} returned {response.status_code}: {response.text.strip()}",
            )
        try:
            payload = response.json()
        except ValueError as e:
            raise LatchkeyGatewayClientError(f"GET {url} returned non-JSON body: {e}") from e
        if not isinstance(payload, dict):
            raise LatchkeyGatewayClientError(f"GET {url} returned non-object JSON: {payload!r}")
        rules = payload.get("rules")
        if not isinstance(rules, list):
            return frozenset()
        scopes_set = set(scopes)
        granted: set[str] = set()
        for rule in rules:
            if not isinstance(rule, dict):
                continue
            for scope_name, permissions in rule.items():
                if scope_name in scopes_set and isinstance(permissions, list):
                    granted.update(p for p in permissions if isinstance(p, str))
        return frozenset(granted)

    def set_permission_rule(
        self,
        permissions_file_path: Path,
        rule_key: str,
        granted_permissions: Sequence[str],
    ) -> None:
        """Add or replace the rule for ``rule_key`` in ``permissions_file_path``.

        Wraps ``POST /permissions/rules?path=<...>&rule_key=<...>`` with
        a JSON-array body of permission-schema names. The extension
        creates the target file if it does not yet exist; it refuses
        any path outside ``LATCHKEY_EXTENSION_PERMISSIONS_ROOT`` with
        a 403, which we surface verbatim so misconfigurations are
        loud.
        """
        url = f"{self.base_url.rstrip('/')}/permissions/rules"
        params = {"path": str(permissions_file_path), "rule_key": rule_key}
        try:
            with self._one_shot_client() as client:
                response = client.post(
                    url,
                    params=params,
                    json=list(granted_permissions),
                    headers=self._build_headers(),
                )
        except httpx.HTTPError as e:
            raise LatchkeyGatewayClientError(f"POST {url} failed: {e}") from e
        if response.status_code >= 400:
            raise LatchkeyGatewayClientError(
                f"POST {url} returned {response.status_code}: {response.text.strip()}",
            )
