import os
import platform
from enum import auto
from typing import Final

from pydantic import SecretStr

from imbue.imbue_common.enums import UpperCaseStrEnum
from imbue.imbue_common.ids import RandomId
from imbue.imbue_common.primitives import NonEmptyStr

# Canonical set of AWS regions the minds app offers for ``LaunchMode.AWS``.
# This is the single source of truth used both to write one
# ``[providers.aws-<region>]`` block per region into the mngr profile settings
# at startup (``imbue.minds.bootstrap``) and to populate the create form's AWS
# region dropdown (``imbue.minds.desktop_client.region_preference``). minds
# deliberately exposes only the US datacenters by default: every configured
# region adds a provider that ``mngr list`` fans out to on each discovery
# cycle, and the non-US regions roughly doubled listing latency for little
# benefit to the current user base. ``mngr_aws`` still ships pinned default
# AMIs for more regions, so this set can be widened later without other
# changes; any region added here must have an AMI in ``mngr_aws`` or it would
# fail AMI resolution at create time. Lives in ``primitives`` (which never
# imports ``mngr``) so the early ``bootstrap`` module can read it without
# violating its no-mngr-on-import contract.
CONFIGURED_AWS_REGIONS: Final[tuple[str, ...]] = (
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
)

# Hardcoded fallback AWS region for the create form when there is no stored
# last-used value and IP geolocation has not (yet) resolved. Must be a member
# of ``CONFIGURED_AWS_REGIONS``.
DEFAULT_AWS_REGION: Final[str] = "us-east-1"


class CreationId(RandomId):
    """Minds-internal handle for an in-flight ``mngr create`` invocation.

    Returned by ``AgentCreator.create_agent_async`` so the desktop client
    UI has something to poll status / stream logs against immediately --
    *before* the inner ``mngr create`` returns and we know the canonical
    ``AgentId`` (the agent id is generated by mngr, not minds, since
    imbue_cloud lease-adoption forces it to the pool host's pre-baked id
    and pre-generating one minds-side led to confusion + bugs).

    Distinct ``"creation-"`` prefix so it can never accidentally be
    typed-checked or string-compared against an ``AgentId``.
    """

    PREFIX = "creation"


class OutputFormat(UpperCaseStrEnum):
    """Output format for command results on stdout."""

    HUMAN = auto()
    JSON = auto()
    JSONL = auto()


class LaunchMode(UpperCaseStrEnum):
    """How a workspace agent should be launched."""

    DOCKER = auto()
    VULTR = auto()
    LIMA = auto()
    IMBUE_CLOUD = auto()
    AWS = auto()
    # Runs the agent in a Modal sandbox using the local machine's own Modal token
    # (``modal token new``) -- resolves the ``modal`` provider instance. Modal
    # sandboxes are ephemeral (~1 day max), so it is surfaced as "Modal (1-day
    # ephemeral)" and is testing-only.
    MODAL = auto()


class DockerRuntime(UpperCaseStrEnum):
    """Container runtime for the local Docker compute provider (``LaunchMode.DOCKER``).

    - ``RUNC`` -- Docker's default runtime. Works everywhere, including macOS.
    - ``RUNSC`` -- gVisor, which intercepts the container's syscalls to shrink
      the host kernel attack surface for untrusted agents. Requires ``runsc`` to
      be installed and registered with the local Docker daemon (Linux in
      practice); it is unavailable on macOS.

    Only meaningful for the Docker compute provider; the other launch modes pin
    their own runtime. The create form defaults this to the platform-appropriate
    value (see :func:`default_docker_runtime`) and lets the user override it
    under advanced settings.
    """

    RUNC = auto()
    RUNSC = auto()


# Env override for the create-form / create-API default runtime, consulted by
# ``default_docker_runtime``. Set it to a ``DockerRuntime`` value
# (case-insensitive) to force the default. CI and the e2e snapshot build set it
# to ``RUNC`` because their Docker daemon has no gVisor (runsc) registered; a
# real deployment leaves it unset, so Linux still defaults to the hardened
# runsc. This is the layer that decides whether the create stacks the
# ``docker_runsc`` template at all -- distinct from
# ``MNGR__PROVIDERS__DOCKER__DOCKER_RUNTIME``, which only overrides the mngr
# provider config and cannot override a template that was explicitly stacked.
_DEFAULT_DOCKER_RUNTIME_ENV_VAR: Final[str] = "MINDS_DOCKER_RUNTIME_DEFAULT"


def default_docker_runtime() -> DockerRuntime:
    """Return the default Docker container runtime for the create form / API.

    An explicit ``MINDS_DOCKER_RUNTIME_DEFAULT`` env override wins when set
    (CI uses it to pin runc, having no gVisor). Otherwise the platform default:
    macOS has no gVisor so it must use runc; Linux defaults to the
    gVisor-hardened runsc (which the minds app assumes is installed there).

    Raises ``ValueError`` if the override is set to a value that is not a
    ``DockerRuntime`` -- a misconfigured knob should fail loud, not silently
    fall back.
    """
    override = os.environ.get(_DEFAULT_DOCKER_RUNTIME_ENV_VAR)
    if override:
        return DockerRuntime(override.strip().upper())
    return DockerRuntime.RUNC if platform.system() == "Darwin" else DockerRuntime.RUNSC


class BackupProvider(UpperCaseStrEnum):
    """How the workspace agent's restic backups are configured.

    Decoupled from both the compute and AI providers so any combination is
    valid. Backup setup runs asynchronously after the host is created; the
    same code path can be re-applied to an existing host later.

    - ``IMBUE_CLOUD`` -- create a per-workspace R2 bucket (named after the
      host id) + a scoped key against the selected account, then inject a
      ``runtime/secrets/restic.env`` pointing restic at that bucket.
      Requires a selected account.
    - ``API_KEY`` -- inject a user-supplied ``KEY=VALUE`` block verbatim
      into ``restic.env``; the user owns ``RESTIC_REPOSITORY`` and any
      backend credentials.
    - ``CONFIGURE_LATER`` -- inject nothing now. Backups stay dormant until
      the same provisioning path is invoked against the host later.
    """

    IMBUE_CLOUD = auto()
    API_KEY = auto()
    CONFIGURE_LATER = auto()


class OneTimeCode(NonEmptyStr):
    """A single-use authentication code for workspace access."""

    ...


class CookieSigningKey(SecretStr):
    """Secret key used for signing authentication cookies."""

    ...


class ServiceName(NonEmptyStr):
    """Name of a service run by an agent (e.g. 'web', 'api')."""

    ...


class GitUrl(NonEmptyStr):
    """A git URL to clone (local path, file://, https://, or ssh)."""

    ...


class GitBranch(NonEmptyStr):
    """A git branch name to clone."""

    ...


class GitCommitHash(NonEmptyStr):
    """A full git commit hash (40 hex characters)."""

    ...
