from enum import auto

from pydantic import SecretStr

from imbue.imbue_common.enums import UpperCaseStrEnum
from imbue.imbue_common.ids import RandomId
from imbue.imbue_common.primitives import NonEmptyStr


class CreationId(RandomId):
    """Minds-internal handle for an in-flight ``mngr create`` invocation.

    Returned by ``AgentCreator.create_agent_async`` so the desktop client
    UI has something to poll status / stream logs against immediately --
    *before* the inner ``mngr create`` returns and we know the canonical
    ``AgentId`` (the agent id is generated by mngr, not minds, since
    imbue_cloud lease-adoption forces it to the pool host's pre-baked id
    and pre-generating one minds-side led to confusion + bugs).

    Distinct ``"creation-"`` prefix so it can never accidentally be
    typed-checked or string-compared against an ``AgentId``.
    """

    PREFIX = "creation"


class OutputFormat(UpperCaseStrEnum):
    """Output format for command results on stdout."""

    HUMAN = auto()
    JSON = auto()
    JSONL = auto()


class LaunchMode(UpperCaseStrEnum):
    """How a workspace agent should be launched."""

    DOCKER = auto()
    CLOUD = auto()
    LIMA = auto()
    IMBUE_CLOUD = auto()


class AIProvider(UpperCaseStrEnum):
    """How the workspace agent should obtain its Anthropic credentials.

    Decoupled from the compute provider so any combination is valid: e.g.
    a user can run on a local container while still using an imbue_cloud-
    minted LiteLLM key for inference.

    - ``IMBUE_CLOUD`` -- mint a LiteLLM virtual key against the selected
      account and inject it as ``ANTHROPIC_API_KEY`` (with the matching
      ``ANTHROPIC_BASE_URL``). Requires a selected account.
    - ``API_KEY`` -- use a user-supplied Anthropic API key directly; no
      ``ANTHROPIC_BASE_URL`` is set so the agent talks to the official
      Anthropic API.
    - ``SUBSCRIPTION`` -- inject neither key nor base URL; the user will
      sign in to Claude interactively once the workspace starts.
    """

    IMBUE_CLOUD = auto()
    API_KEY = auto()
    SUBSCRIPTION = auto()


class BackupProvider(UpperCaseStrEnum):
    """How the workspace agent's restic backups are configured.

    Decoupled from both the compute and AI providers so any combination is
    valid. Backup setup runs asynchronously after the host is created; the
    same code path can be re-applied to an existing host later.

    - ``IMBUE_CLOUD`` -- create a per-workspace R2 bucket (named after the
      host id) + a scoped key against the selected account, then inject a
      ``runtime/secrets/restic.env`` pointing restic at that bucket.
      Requires a selected account.
    - ``API_KEY`` -- inject a user-supplied ``KEY=VALUE`` block verbatim
      into ``restic.env``; the user owns ``RESTIC_REPOSITORY`` and any
      backend credentials.
    - ``CONFIGURE_LATER`` -- inject nothing now. Backups stay dormant until
      the same provisioning path is invoked against the host later.
    """

    IMBUE_CLOUD = auto()
    API_KEY = auto()
    CONFIGURE_LATER = auto()


class BackupEncryptionMethod(UpperCaseStrEnum):
    """How the restic repository for a workspace's backups is encrypted.

    Only meaningful when a real backup provider (``IMBUE_CLOUD`` or
    ``API_KEY``) is selected.

    - ``MASTER_PASSWORD`` -- encrypt the repo with a passphrase. The value
      is established once and stored in a per-user file, shared across all
      of the user's workspaces.
    - ``NO_PASSWORD`` -- use an empty-password repo; restic runs with
      ``--insecure-no-password`` and ``backup.toml`` records
      ``restic.allow_empty_password = true``.
    """

    MASTER_PASSWORD = auto()
    NO_PASSWORD = auto()


class OneTimeCode(NonEmptyStr):
    """A single-use authentication code for workspace access."""

    ...


class CookieSigningKey(SecretStr):
    """Secret key used for signing authentication cookies."""

    ...


class ServiceName(NonEmptyStr):
    """Name of a service run by an agent (e.g. 'web', 'api')."""

    ...


class GitUrl(NonEmptyStr):
    """A git URL to clone (local path, file://, https://, or ssh)."""

    ...


class GitBranch(NonEmptyStr):
    """A git branch name to clone."""

    ...


class GitCommitHash(NonEmptyStr):
    """A full git commit hash (40 hex characters)."""

    ...
